// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xai/api/v1/auth.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XaiApi {

  /// <summary>Holder for reflection information generated from xai/api/v1/auth.proto</summary>
  public static partial class AuthReflection {

    #region Descriptor
    /// <summary>File descriptor for xai/api/v1/auth.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AuthReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV4YWkvYXBpL3YxL2F1dGgucHJvdG8SB3hhaV9hcGkaG2dvb2dsZS9wcm90",
            "b2J1Zi9lbXB0eS5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5w",
            "cm90byKsAwoGQXBpS2V5EigKEHJlZGFjdGVkX2FwaV9rZXkYASABKAlSDnJl",
            "ZGFjdGVkQXBpS2V5EhcKB3VzZXJfaWQYAyABKAlSBnVzZXJJZBISCgRuYW1l",
            "GAQgASgJUgRuYW1lEjsKC2NyZWF0ZV90aW1lGAUgASgLMhouZ29vZ2xlLnBy",
            "b3RvYnVmLlRpbWVzdGFtcFIKY3JlYXRlVGltZRI7Cgttb2RpZnlfdGltZRgJ",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBSCm1vZGlmeVRpbWUS",
            "HwoLbW9kaWZpZWRfYnkYCyABKAlSCm1vZGlmaWVkQnkSFwoHdGVhbV9pZBgG",
            "IAEoCVIGdGVhbUlkEhIKBGFjbHMYByADKAlSBGFjbHMSHAoKYXBpX2tleV9p",
            "ZBgIIAEoCVIIYXBpS2V5SWQSJgoPYXBpX2tleV9ibG9ja2VkGAogASgIUg1h",
            "cGlLZXlCbG9ja2VkEiEKDHRlYW1fYmxvY2tlZBgNIAEoCFILdGVhbUJsb2Nr",
            "ZWQSGgoIZGlzYWJsZWQYDCABKAhSCGRpc2FibGVkMkUKBEF1dGgSPQoQZ2V0",
            "X2FwaV9rZXlfaW5mbxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoPLnhhaV9h",
            "cGkuQXBpS2V5IgBCUAoLY29tLnhhaV9hcGlCCUF1dGhQcm90b1ABogIDWFhY",
            "qgIGWGFpQXBpygIGWGFpQXBp4gISWGFpQXBpXEdQQk1ldGFkYXRh6gIGWGFp",
            "QXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.ApiKey), global::XaiApi.ApiKey.Parser, new[]{ "RedactedApiKey", "UserId", "Name", "CreateTime", "ModifyTime", "ModifiedBy", "TeamId", "Acls", "ApiKeyId", "ApiKeyBlocked", "TeamBlocked", "Disabled" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// API key information.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApiKey : pb::IMessage<ApiKey>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiKey> _parser = new pb::MessageParser<ApiKey>(() => new ApiKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApiKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.AuthReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiKey(ApiKey other) : this() {
      redactedApiKey_ = other.redactedApiKey_;
      userId_ = other.userId_;
      name_ = other.name_;
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      modifyTime_ = other.modifyTime_ != null ? other.modifyTime_.Clone() : null;
      modifiedBy_ = other.modifiedBy_;
      teamId_ = other.teamId_;
      acls_ = other.acls_.Clone();
      apiKeyId_ = other.apiKeyId_;
      apiKeyBlocked_ = other.apiKeyBlocked_;
      teamBlocked_ = other.teamBlocked_;
      disabled_ = other.disabled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiKey Clone() {
      return new ApiKey(this);
    }

    /// <summary>Field number for the "redacted_api_key" field.</summary>
    public const int RedactedApiKeyFieldNumber = 1;
    private string redactedApiKey_ = "";
    /// <summary>
    /// A redacted API key. The full API key will not be displayed after it has
    /// been created.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RedactedApiKey {
      get { return redactedApiKey_; }
      set {
        redactedApiKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 3;
    private string userId_ = "";
    /// <summary>
    /// ID of the user who created this API key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    /// <summary>
    /// Human-readable name for the API key.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// Unix timestamp when the API key was created.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "modify_time" field.</summary>
    public const int ModifyTimeFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp modifyTime_;
    /// <summary>
    /// Unix timestamp when the API key was last modified.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ModifyTime {
      get { return modifyTime_; }
      set {
        modifyTime_ = value;
      }
    }

    /// <summary>Field number for the "modified_by" field.</summary>
    public const int ModifiedByFieldNumber = 11;
    private string modifiedBy_ = "";
    /// <summary>
    /// ID of the last user who modified the API key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModifiedBy {
      get { return modifiedBy_; }
      set {
        modifiedBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "team_id" field.</summary>
    public const int TeamIdFieldNumber = 6;
    private string teamId_ = "";
    /// <summary>
    /// ID of the team this API key belongs to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TeamId {
      get { return teamId_; }
      set {
        teamId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "acls" field.</summary>
    public const int AclsFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_acls_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> acls_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Access Control Lists (ACLs) associated with this key.
    /// These indicate the resources that the API key has access to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Acls {
      get { return acls_; }
    }

    /// <summary>Field number for the "api_key_id" field.</summary>
    public const int ApiKeyIdFieldNumber = 8;
    private string apiKeyId_ = "";
    /// <summary>
    /// The ID of the API key. This is different from the API key itself.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApiKeyId {
      get { return apiKeyId_; }
      set {
        apiKeyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "api_key_blocked" field.</summary>
    public const int ApiKeyBlockedFieldNumber = 10;
    private bool apiKeyBlocked_;
    /// <summary>
    /// Whether the API key is currently blocked from making API requests.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ApiKeyBlocked {
      get { return apiKeyBlocked_; }
      set {
        apiKeyBlocked_ = value;
      }
    }

    /// <summary>Field number for the "team_blocked" field.</summary>
    public const int TeamBlockedFieldNumber = 13;
    private bool teamBlocked_;
    /// <summary>
    /// Whether the team is currently blocked from making API requests.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TeamBlocked {
      get { return teamBlocked_; }
      set {
        teamBlocked_ = value;
      }
    }

    /// <summary>Field number for the "disabled" field.</summary>
    public const int DisabledFieldNumber = 12;
    private bool disabled_;
    /// <summary>
    /// Whether the API key is currently disabled.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Disabled {
      get { return disabled_; }
      set {
        disabled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApiKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApiKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RedactedApiKey != other.RedactedApiKey) return false;
      if (UserId != other.UserId) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(ModifyTime, other.ModifyTime)) return false;
      if (ModifiedBy != other.ModifiedBy) return false;
      if (TeamId != other.TeamId) return false;
      if(!acls_.Equals(other.acls_)) return false;
      if (ApiKeyId != other.ApiKeyId) return false;
      if (ApiKeyBlocked != other.ApiKeyBlocked) return false;
      if (TeamBlocked != other.TeamBlocked) return false;
      if (Disabled != other.Disabled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RedactedApiKey.Length != 0) hash ^= RedactedApiKey.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (modifyTime_ != null) hash ^= ModifyTime.GetHashCode();
      if (ModifiedBy.Length != 0) hash ^= ModifiedBy.GetHashCode();
      if (TeamId.Length != 0) hash ^= TeamId.GetHashCode();
      hash ^= acls_.GetHashCode();
      if (ApiKeyId.Length != 0) hash ^= ApiKeyId.GetHashCode();
      if (ApiKeyBlocked != false) hash ^= ApiKeyBlocked.GetHashCode();
      if (TeamBlocked != false) hash ^= TeamBlocked.GetHashCode();
      if (Disabled != false) hash ^= Disabled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RedactedApiKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RedactedApiKey);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CreateTime);
      }
      if (TeamId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TeamId);
      }
      acls_.WriteTo(output, _repeated_acls_codec);
      if (ApiKeyId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ApiKeyId);
      }
      if (modifyTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ModifyTime);
      }
      if (ApiKeyBlocked != false) {
        output.WriteRawTag(80);
        output.WriteBool(ApiKeyBlocked);
      }
      if (ModifiedBy.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ModifiedBy);
      }
      if (Disabled != false) {
        output.WriteRawTag(96);
        output.WriteBool(Disabled);
      }
      if (TeamBlocked != false) {
        output.WriteRawTag(104);
        output.WriteBool(TeamBlocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RedactedApiKey.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RedactedApiKey);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (createTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CreateTime);
      }
      if (TeamId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TeamId);
      }
      acls_.WriteTo(ref output, _repeated_acls_codec);
      if (ApiKeyId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ApiKeyId);
      }
      if (modifyTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ModifyTime);
      }
      if (ApiKeyBlocked != false) {
        output.WriteRawTag(80);
        output.WriteBool(ApiKeyBlocked);
      }
      if (ModifiedBy.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ModifiedBy);
      }
      if (Disabled != false) {
        output.WriteRawTag(96);
        output.WriteBool(Disabled);
      }
      if (TeamBlocked != false) {
        output.WriteRawTag(104);
        output.WriteBool(TeamBlocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RedactedApiKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RedactedApiKey);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (modifyTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModifyTime);
      }
      if (ModifiedBy.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModifiedBy);
      }
      if (TeamId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TeamId);
      }
      size += acls_.CalculateSize(_repeated_acls_codec);
      if (ApiKeyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiKeyId);
      }
      if (ApiKeyBlocked != false) {
        size += 1 + 1;
      }
      if (TeamBlocked != false) {
        size += 1 + 1;
      }
      if (Disabled != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApiKey other) {
      if (other == null) {
        return;
      }
      if (other.RedactedApiKey.Length != 0) {
        RedactedApiKey = other.RedactedApiKey;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.modifyTime_ != null) {
        if (modifyTime_ == null) {
          ModifyTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ModifyTime.MergeFrom(other.ModifyTime);
      }
      if (other.ModifiedBy.Length != 0) {
        ModifiedBy = other.ModifiedBy;
      }
      if (other.TeamId.Length != 0) {
        TeamId = other.TeamId;
      }
      acls_.Add(other.acls_);
      if (other.ApiKeyId.Length != 0) {
        ApiKeyId = other.ApiKeyId;
      }
      if (other.ApiKeyBlocked != false) {
        ApiKeyBlocked = other.ApiKeyBlocked;
      }
      if (other.TeamBlocked != false) {
        TeamBlocked = other.TeamBlocked;
      }
      if (other.Disabled != false) {
        Disabled = other.Disabled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RedactedApiKey = input.ReadString();
            break;
          }
          case 26: {
            UserId = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 50: {
            TeamId = input.ReadString();
            break;
          }
          case 58: {
            acls_.AddEntriesFrom(input, _repeated_acls_codec);
            break;
          }
          case 66: {
            ApiKeyId = input.ReadString();
            break;
          }
          case 74: {
            if (modifyTime_ == null) {
              ModifyTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ModifyTime);
            break;
          }
          case 80: {
            ApiKeyBlocked = input.ReadBool();
            break;
          }
          case 90: {
            ModifiedBy = input.ReadString();
            break;
          }
          case 96: {
            Disabled = input.ReadBool();
            break;
          }
          case 104: {
            TeamBlocked = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RedactedApiKey = input.ReadString();
            break;
          }
          case 26: {
            UserId = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 50: {
            TeamId = input.ReadString();
            break;
          }
          case 58: {
            acls_.AddEntriesFrom(ref input, _repeated_acls_codec);
            break;
          }
          case 66: {
            ApiKeyId = input.ReadString();
            break;
          }
          case 74: {
            if (modifyTime_ == null) {
              ModifyTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ModifyTime);
            break;
          }
          case 80: {
            ApiKeyBlocked = input.ReadBool();
            break;
          }
          case 90: {
            ModifiedBy = input.ReadString();
            break;
          }
          case 96: {
            Disabled = input.ReadBool();
            break;
          }
          case 104: {
            TeamBlocked = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
