// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xai/api/v1/chat.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace XaiApi {
  /// <summary>
  /// An API that exposes our language models via a Chat interface.
  /// </summary>
  public static partial class Chat
  {
    static readonly string __ServiceName = "xai_api.Chat";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetCompletionsRequest> __Marshaller_xai_api_GetCompletionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetCompletionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetChatCompletionResponse> __Marshaller_xai_api_GetChatCompletionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetChatCompletionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetChatCompletionChunk> __Marshaller_xai_api_GetChatCompletionChunk = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetChatCompletionChunk.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.StartDeferredResponse> __Marshaller_xai_api_StartDeferredResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.StartDeferredResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetDeferredRequest> __Marshaller_xai_api_GetDeferredRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetDeferredRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetDeferredCompletionResponse> __Marshaller_xai_api_GetDeferredCompletionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetDeferredCompletionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.GetStoredCompletionRequest> __Marshaller_xai_api_GetStoredCompletionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.GetStoredCompletionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.DeleteStoredCompletionRequest> __Marshaller_xai_api_DeleteStoredCompletionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.DeleteStoredCompletionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::XaiApi.DeleteStoredCompletionResponse> __Marshaller_xai_api_DeleteStoredCompletionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::XaiApi.DeleteStoredCompletionResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionResponse> __Method_GetCompletion = new grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCompletion",
        __Marshaller_xai_api_GetCompletionsRequest,
        __Marshaller_xai_api_GetChatCompletionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionChunk> __Method_GetCompletionChunk = new grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionChunk>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetCompletionChunk",
        __Marshaller_xai_api_GetCompletionsRequest,
        __Marshaller_xai_api_GetChatCompletionChunk);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.StartDeferredResponse> __Method_StartDeferredCompletion = new grpc::Method<global::XaiApi.GetCompletionsRequest, global::XaiApi.StartDeferredResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartDeferredCompletion",
        __Marshaller_xai_api_GetCompletionsRequest,
        __Marshaller_xai_api_StartDeferredResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.GetDeferredRequest, global::XaiApi.GetDeferredCompletionResponse> __Method_GetDeferredCompletion = new grpc::Method<global::XaiApi.GetDeferredRequest, global::XaiApi.GetDeferredCompletionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDeferredCompletion",
        __Marshaller_xai_api_GetDeferredRequest,
        __Marshaller_xai_api_GetDeferredCompletionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.GetStoredCompletionRequest, global::XaiApi.GetChatCompletionResponse> __Method_GetStoredCompletion = new grpc::Method<global::XaiApi.GetStoredCompletionRequest, global::XaiApi.GetChatCompletionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetStoredCompletion",
        __Marshaller_xai_api_GetStoredCompletionRequest,
        __Marshaller_xai_api_GetChatCompletionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::XaiApi.DeleteStoredCompletionRequest, global::XaiApi.DeleteStoredCompletionResponse> __Method_DeleteStoredCompletion = new grpc::Method<global::XaiApi.DeleteStoredCompletionRequest, global::XaiApi.DeleteStoredCompletionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteStoredCompletion",
        __Marshaller_xai_api_DeleteStoredCompletionRequest,
        __Marshaller_xai_api_DeleteStoredCompletionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::XaiApi.ChatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Chat</summary>
    [grpc::BindServiceMethod(typeof(Chat), "BindService")]
    public abstract partial class ChatBase
    {
      /// <summary>
      /// Samples a response from the model and blocks until the response has been
      /// fully generated.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XaiApi.GetChatCompletionResponse> GetCompletion(global::XaiApi.GetCompletionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Samples a response from the model and streams out the model tokens as they
      /// are being generated.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetCompletionChunk(global::XaiApi.GetCompletionsRequest request, grpc::IServerStreamWriter<global::XaiApi.GetChatCompletionChunk> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Starts sampling of the model and immediately returns a response containing
      /// a request id. The request id may be used to poll
      /// the `GetDeferredCompletion` RPC.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XaiApi.StartDeferredResponse> StartDeferredCompletion(global::XaiApi.GetCompletionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Gets the result of a deferred completion started by calling `StartDeferredCompletion`.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XaiApi.GetDeferredCompletionResponse> GetDeferredCompletion(global::XaiApi.GetDeferredRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Retrieve a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XaiApi.GetChatCompletionResponse> GetStoredCompletion(global::XaiApi.GetStoredCompletionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Delete a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::XaiApi.DeleteStoredCompletionResponse> DeleteStoredCompletion(global::XaiApi.DeleteStoredCompletionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Chat</summary>
    public partial class ChatClient : grpc::ClientBase<ChatClient>
    {
      /// <summary>Creates a new client for Chat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ChatClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Chat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ChatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ChatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Samples a response from the model and blocks until the response has been
      /// fully generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetChatCompletionResponse GetCompletion(global::XaiApi.GetCompletionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompletion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Samples a response from the model and blocks until the response has been
      /// fully generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetChatCompletionResponse GetCompletion(global::XaiApi.GetCompletionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCompletion, null, options, request);
      }
      /// <summary>
      /// Samples a response from the model and blocks until the response has been
      /// fully generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetChatCompletionResponse> GetCompletionAsync(global::XaiApi.GetCompletionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompletionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Samples a response from the model and blocks until the response has been
      /// fully generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetChatCompletionResponse> GetCompletionAsync(global::XaiApi.GetCompletionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCompletion, null, options, request);
      }
      /// <summary>
      /// Samples a response from the model and streams out the model tokens as they
      /// are being generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::XaiApi.GetChatCompletionChunk> GetCompletionChunk(global::XaiApi.GetCompletionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCompletionChunk(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Samples a response from the model and streams out the model tokens as they
      /// are being generated.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::XaiApi.GetChatCompletionChunk> GetCompletionChunk(global::XaiApi.GetCompletionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetCompletionChunk, null, options, request);
      }
      /// <summary>
      /// Starts sampling of the model and immediately returns a response containing
      /// a request id. The request id may be used to poll
      /// the `GetDeferredCompletion` RPC.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.StartDeferredResponse StartDeferredCompletion(global::XaiApi.GetCompletionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartDeferredCompletion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Starts sampling of the model and immediately returns a response containing
      /// a request id. The request id may be used to poll
      /// the `GetDeferredCompletion` RPC.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.StartDeferredResponse StartDeferredCompletion(global::XaiApi.GetCompletionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartDeferredCompletion, null, options, request);
      }
      /// <summary>
      /// Starts sampling of the model and immediately returns a response containing
      /// a request id. The request id may be used to poll
      /// the `GetDeferredCompletion` RPC.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.StartDeferredResponse> StartDeferredCompletionAsync(global::XaiApi.GetCompletionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartDeferredCompletionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Starts sampling of the model and immediately returns a response containing
      /// a request id. The request id may be used to poll
      /// the `GetDeferredCompletion` RPC.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.StartDeferredResponse> StartDeferredCompletionAsync(global::XaiApi.GetCompletionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartDeferredCompletion, null, options, request);
      }
      /// <summary>
      /// Gets the result of a deferred completion started by calling `StartDeferredCompletion`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetDeferredCompletionResponse GetDeferredCompletion(global::XaiApi.GetDeferredRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDeferredCompletion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the result of a deferred completion started by calling `StartDeferredCompletion`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetDeferredCompletionResponse GetDeferredCompletion(global::XaiApi.GetDeferredRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDeferredCompletion, null, options, request);
      }
      /// <summary>
      /// Gets the result of a deferred completion started by calling `StartDeferredCompletion`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetDeferredCompletionResponse> GetDeferredCompletionAsync(global::XaiApi.GetDeferredRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDeferredCompletionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the result of a deferred completion started by calling `StartDeferredCompletion`.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetDeferredCompletionResponse> GetDeferredCompletionAsync(global::XaiApi.GetDeferredRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDeferredCompletion, null, options, request);
      }
      /// <summary>
      /// Retrieve a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetChatCompletionResponse GetStoredCompletion(global::XaiApi.GetStoredCompletionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStoredCompletion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.GetChatCompletionResponse GetStoredCompletion(global::XaiApi.GetStoredCompletionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetStoredCompletion, null, options, request);
      }
      /// <summary>
      /// Retrieve a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetChatCompletionResponse> GetStoredCompletionAsync(global::XaiApi.GetStoredCompletionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStoredCompletionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.GetChatCompletionResponse> GetStoredCompletionAsync(global::XaiApi.GetStoredCompletionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetStoredCompletion, null, options, request);
      }
      /// <summary>
      /// Delete a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.DeleteStoredCompletionResponse DeleteStoredCompletion(global::XaiApi.DeleteStoredCompletionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteStoredCompletion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::XaiApi.DeleteStoredCompletionResponse DeleteStoredCompletion(global::XaiApi.DeleteStoredCompletionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteStoredCompletion, null, options, request);
      }
      /// <summary>
      /// Delete a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.DeleteStoredCompletionResponse> DeleteStoredCompletionAsync(global::XaiApi.DeleteStoredCompletionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteStoredCompletionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Delete a stored response using the response ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::XaiApi.DeleteStoredCompletionResponse> DeleteStoredCompletionAsync(global::XaiApi.DeleteStoredCompletionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteStoredCompletion, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ChatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ChatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCompletion, serviceImpl.GetCompletion)
          .AddMethod(__Method_GetCompletionChunk, serviceImpl.GetCompletionChunk)
          .AddMethod(__Method_StartDeferredCompletion, serviceImpl.StartDeferredCompletion)
          .AddMethod(__Method_GetDeferredCompletion, serviceImpl.GetDeferredCompletion)
          .AddMethod(__Method_GetStoredCompletion, serviceImpl.GetStoredCompletion)
          .AddMethod(__Method_DeleteStoredCompletion, serviceImpl.DeleteStoredCompletion).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ChatBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCompletion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionResponse>(serviceImpl.GetCompletion));
      serviceBinder.AddMethod(__Method_GetCompletionChunk, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::XaiApi.GetCompletionsRequest, global::XaiApi.GetChatCompletionChunk>(serviceImpl.GetCompletionChunk));
      serviceBinder.AddMethod(__Method_StartDeferredCompletion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XaiApi.GetCompletionsRequest, global::XaiApi.StartDeferredResponse>(serviceImpl.StartDeferredCompletion));
      serviceBinder.AddMethod(__Method_GetDeferredCompletion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XaiApi.GetDeferredRequest, global::XaiApi.GetDeferredCompletionResponse>(serviceImpl.GetDeferredCompletion));
      serviceBinder.AddMethod(__Method_GetStoredCompletion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XaiApi.GetStoredCompletionRequest, global::XaiApi.GetChatCompletionResponse>(serviceImpl.GetStoredCompletion));
      serviceBinder.AddMethod(__Method_DeleteStoredCompletion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::XaiApi.DeleteStoredCompletionRequest, global::XaiApi.DeleteStoredCompletionResponse>(serviceImpl.DeleteStoredCompletion));
    }

  }
}
#endregion
