// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xai/api/v1/image.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XaiApi {

  /// <summary>Holder for reflection information generated from xai/api/v1/image.proto</summary>
  public static partial class ImageReflection {

    #region Descriptor
    /// <summary>File descriptor for xai/api/v1/image.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ4YWkvYXBpL3YxL2ltYWdlLnByb3RvEgd4YWlfYXBpGhZ4YWkvYXBpL3Yx",
            "L3VzYWdlLnByb3RvIvcCChRHZW5lcmF0ZUltYWdlUmVxdWVzdBIWCgZwcm9t",
            "cHQYASABKAlSBnByb21wdBIuCgVpbWFnZRgFIAEoCzIYLnhhaV9hcGkuSW1h",
            "Z2VVcmxDb250ZW50UgVpbWFnZRIUCgVtb2RlbBgCIAEoCVIFbW9kZWwSEQoB",
            "bhgDIAEoBUgAUgFuiAEBEhIKBHVzZXIYBCABKAlSBHVzZXISLAoGZm9ybWF0",
            "GAsgASgOMhQueGFpX2FwaS5JbWFnZUZvcm1hdFIGZm9ybWF0EkEKDGFzcGVj",
            "dF9yYXRpbxgOIAEoDjIZLnhhaV9hcGkuSW1hZ2VBc3BlY3RSYXRpb0gBUgth",
            "c3BlY3RSYXRpb4gBARI9CgpyZXNvbHV0aW9uGA8gASgOMhgueGFpX2FwaS5J",
            "bWFnZVJlc29sdXRpb25IAlIKcmVzb2x1dGlvbogBAUIECgJfbkIPCg1fYXNw",
            "ZWN0X3JhdGlvQg0KC19yZXNvbHV0aW9uSgQIDRAOIoQBCg1JbWFnZVJlc3Bv",
            "bnNlEi8KBmltYWdlcxgBIAMoCzIXLnhhaV9hcGkuR2VuZXJhdGVkSW1hZ2VS",
            "BmltYWdlcxIUCgVtb2RlbBgCIAEoCVIFbW9kZWwSLAoFdXNhZ2UYAyABKAsy",
            "Fi54YWlfYXBpLlNhbXBsaW5nVXNhZ2VSBXVzYWdlInwKDkdlbmVyYXRlZElt",
            "YWdlEhgKBmJhc2U2NBgBIAEoCUgAUgZiYXNlNjQSEgoDdXJsGAMgASgJSABS",
            "A3VybBItChJyZXNwZWN0X21vZGVyYXRpb24YBCABKAhSEXJlc3BlY3RNb2Rl",
            "cmF0aW9uQgcKBWltYWdlSgQIAhADIlwKD0ltYWdlVXJsQ29udGVudBIbCglp",
            "bWFnZV91cmwYASABKAlSCGltYWdlVXJsEiwKBmRldGFpbBgCIAEoDjIULnhh",
            "aV9hcGkuSW1hZ2VEZXRhaWxSBmRldGFpbCpTCgtJbWFnZURldGFpbBISCg5E",
            "RVRBSUxfSU5WQUxJRBAAEg8KC0RFVEFJTF9BVVRPEAESDgoKREVUQUlMX0xP",
            "VxACEg8KC0RFVEFJTF9ISUdIEAMqUAoLSW1hZ2VGb3JtYXQSFgoSSU1HX0ZP",
            "Uk1BVF9JTlZBTElEEAASFQoRSU1HX0ZPUk1BVF9CQVNFNjQQARISCg5JTUdf",
            "Rk9STUFUX1VSTBACKmoKDEltYWdlUXVhbGl0eRIXChNJTUdfUVVBTElUWV9J",
            "TlZBTElEEAASEwoPSU1HX1FVQUxJVFlfTE9XEAESFgoSSU1HX1FVQUxJVFlf",
            "TUVESVVNEAISFAoQSU1HX1FVQUxJVFlfSElHSBADKqcDChBJbWFnZUFzcGVj",
            "dFJhdGlvEhwKGElNR19BU1BFQ1RfUkFUSU9fSU5WQUxJRBAAEhgKFElNR19B",
            "U1BFQ1RfUkFUSU9fMV8xEAESGAoUSU1HX0FTUEVDVF9SQVRJT18zXzQQAhIY",
            "ChRJTUdfQVNQRUNUX1JBVElPXzRfMxADEhkKFUlNR19BU1BFQ1RfUkFUSU9f",
            "OV8xNhAEEhkKFUlNR19BU1BFQ1RfUkFUSU9fMTZfORAFEhgKFElNR19BU1BF",
            "Q1RfUkFUSU9fMl8zEAYSGAoUSU1HX0FTUEVDVF9SQVRJT18zXzIQBxIZChVJ",
            "TUdfQVNQRUNUX1JBVElPX0FVVE8QCBIbChdJTUdfQVNQRUNUX1JBVElPXzlf",
            "MTlfNRAJEhsKF0lNR19BU1BFQ1RfUkFUSU9fMTlfNV85EAoSGQoVSU1HX0FT",
            "UEVDVF9SQVRJT185XzIwEAsSGQoVSU1HX0FTUEVDVF9SQVRJT18yMF85EAwS",
            "GAoUSU1HX0FTUEVDVF9SQVRJT18xXzIQDRIYChRJTUdfQVNQRUNUX1JBVElP",
            "XzJfMRAOKlsKD0ltYWdlUmVzb2x1dGlvbhIaChZJTUdfUkVTT0xVVElPTl9J",
            "TlZBTElEEAASFQoRSU1HX1JFU09MVVRJT05fMUsQARIVChFJTUdfUkVTT0xV",
            "VElPTl8ySxACMlEKBUltYWdlEkgKDUdlbmVyYXRlSW1hZ2USHS54YWlfYXBp",
            "LkdlbmVyYXRlSW1hZ2VSZXF1ZXN0GhYueGFpX2FwaS5JbWFnZVJlc3BvbnNl",
            "IgBCUQoLY29tLnhhaV9hcGlCCkltYWdlUHJvdG9QAaICA1hYWKoCBlhhaUFw",
            "acoCBlhhaUFwaeICElhhaUFwaVxHUEJNZXRhZGF0YeoCBlhhaUFwaWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::XaiApi.UsageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XaiApi.ImageDetail), typeof(global::XaiApi.ImageFormat), typeof(global::XaiApi.ImageQuality), typeof(global::XaiApi.ImageAspectRatio), typeof(global::XaiApi.ImageResolution), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.GenerateImageRequest), global::XaiApi.GenerateImageRequest.Parser, new[]{ "Prompt", "Image", "Model", "N", "User", "Format", "AspectRatio", "Resolution" }, new[]{ "N", "AspectRatio", "Resolution" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.ImageResponse), global::XaiApi.ImageResponse.Parser, new[]{ "Images", "Model", "Usage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.GeneratedImage), global::XaiApi.GeneratedImage.Parser, new[]{ "Base64", "Url", "RespectModeration" }, new[]{ "Image" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.ImageUrlContent), global::XaiApi.ImageUrlContent.Parser, new[]{ "ImageUrl", "Detail" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Indicates the level of preprocessing to apply to images that will be fed to
  /// the model.
  /// </summary>
  public enum ImageDetail {
    /// <summary>
    /// Detail level is invalid.
    /// </summary>
    [pbr::OriginalName("DETAIL_INVALID")] DetailInvalid = 0,
    /// <summary>
    /// The system will decide the image resolution to use.
    /// </summary>
    [pbr::OriginalName("DETAIL_AUTO")] DetailAuto = 1,
    /// <summary>
    /// The model will process a low-resolution version of the image. This is
    /// faster and cheaper (i.e. consumes fewer tokens).
    /// </summary>
    [pbr::OriginalName("DETAIL_LOW")] DetailLow = 2,
    /// <summary>
    /// The model will process a high-resolution of the image. This is slower and
    /// more expensive but will allow the model to attend to more nuanced details
    /// in the image.
    /// </summary>
    [pbr::OriginalName("DETAIL_HIGH")] DetailHigh = 3,
  }

  /// <summary>
  /// The image format to be returned (base-64 encoded string or a url of
  /// the image).
  /// </summary>
  public enum ImageFormat {
    /// <summary>
    /// Image format is invalid.
    /// </summary>
    [pbr::OriginalName("IMG_FORMAT_INVALID")] ImgFormatInvalid = 0,
    /// <summary>
    /// A base-64 encoding of the image.
    /// </summary>
    [pbr::OriginalName("IMG_FORMAT_BASE64")] ImgFormatBase64 = 1,
    /// <summary>
    /// An URL at which the user can download the image.
    /// </summary>
    [pbr::OriginalName("IMG_FORMAT_URL")] ImgFormatUrl = 2,
  }

  /// <summary>
  /// Quality levels for image generation with their corresponding resolutions.
  /// Currently only supported by grok-imagine models.
  /// </summary>
  public enum ImageQuality {
    /// <summary>
    /// Quality is invalid.
    /// </summary>
    [pbr::OriginalName("IMG_QUALITY_INVALID")] ImgQualityInvalid = 0,
    /// <summary>
    /// Low quality.
    /// </summary>
    [pbr::OriginalName("IMG_QUALITY_LOW")] ImgQualityLow = 1,
    /// <summary>
    /// Medium quality: (default).
    /// </summary>
    [pbr::OriginalName("IMG_QUALITY_MEDIUM")] ImgQualityMedium = 2,
    /// <summary>
    /// High quality.
    /// </summary>
    [pbr::OriginalName("IMG_QUALITY_HIGH")] ImgQualityHigh = 3,
  }

  /// <summary>
  /// Aspect ratio for image generation.
  /// Only supported by grok-imagine models.
  /// </summary>
  public enum ImageAspectRatio {
    /// <summary>
    /// Invalid aspect ratio.
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_INVALID")] ImgAspectRatioInvalid = 0,
    /// <summary>
    /// 1:1 aspect ratio (square).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_1_1")] ImgAspectRatio11 = 1,
    /// <summary>
    /// 3:4 aspect ratio (portrait).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_3_4")] ImgAspectRatio34 = 2,
    /// <summary>
    /// 4:3 aspect ratio (landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_4_3")] ImgAspectRatio43 = 3,
    /// <summary>
    /// 9:16 aspect ratio (tall portrait).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_9_16")] ImgAspectRatio916 = 4,
    /// <summary>
    /// 16:9 aspect ratio (wide landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_16_9")] ImgAspectRatio169 = 5,
    /// <summary>
    /// 2:3 aspect ratio (photo portrait).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_2_3")] ImgAspectRatio23 = 6,
    /// <summary>
    /// 3:2 aspect ratio (photo landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_3_2")] ImgAspectRatio32 = 7,
    /// <summary>
    /// Auto aspect ratio (model auto-selects based on prompt).
    /// Only supported for image generation with a thinking upsampler.
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_AUTO")] ImgAspectRatioAuto = 8,
    /// <summary>
    /// 9:19.5 aspect ratio (extra tall portrait - phone screens).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_9_19_5")] ImgAspectRatio9195 = 9,
    /// <summary>
    /// 19.5:9 aspect ratio (extra wide landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_19_5_9")] ImgAspectRatio1959 = 10,
    /// <summary>
    /// 9:20 aspect ratio (tall portrait - modern phone screens).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_9_20")] ImgAspectRatio920 = 11,
    /// <summary>
    /// 20:9 aspect ratio (ultra wide landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_20_9")] ImgAspectRatio209 = 12,
    /// <summary>
    /// 1:2 aspect ratio (tall portrait).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_1_2")] ImgAspectRatio12 = 13,
    /// <summary>
    /// 2:1 aspect ratio (wide landscape).
    /// </summary>
    [pbr::OriginalName("IMG_ASPECT_RATIO_2_1")] ImgAspectRatio21 = 14,
  }

  /// <summary>
  /// Resolution for image generation.
  /// Only supported by grok-imagine models.
  /// </summary>
  public enum ImageResolution {
    /// <summary>
    /// Invalid resolution.
    /// </summary>
    [pbr::OriginalName("IMG_RESOLUTION_INVALID")] ImgResolutionInvalid = 0,
    /// <summary>
    /// 1k resolution (~1 megapixel total).
    /// Dimensions vary by aspect ratio.
    /// </summary>
    [pbr::OriginalName("IMG_RESOLUTION_1K")] ImgResolution1K = 1,
    /// <summary>
    /// 2k resolution (~4 megapixel total).
    /// </summary>
    [pbr::OriginalName("IMG_RESOLUTION_2K")] ImgResolution2K = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Request message for generating an image.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GenerateImageRequest : pb::IMessage<GenerateImageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateImageRequest> _parser = new pb::MessageParser<GenerateImageRequest>(() => new GenerateImageRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateImageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.ImageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateImageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateImageRequest(GenerateImageRequest other) : this() {
      _hasBits0 = other._hasBits0;
      prompt_ = other.prompt_;
      image_ = other.image_ != null ? other.image_.Clone() : null;
      model_ = other.model_;
      n_ = other.n_;
      user_ = other.user_;
      format_ = other.format_;
      aspectRatio_ = other.aspectRatio_;
      resolution_ = other.resolution_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateImageRequest Clone() {
      return new GenerateImageRequest(this);
    }

    /// <summary>Field number for the "prompt" field.</summary>
    public const int PromptFieldNumber = 1;
    private string prompt_ = "";
    /// <summary>
    /// Input prompt to generate an image from.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prompt {
      get { return prompt_; }
      set {
        prompt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image" field.</summary>
    public const int ImageFieldNumber = 5;
    private global::XaiApi.ImageUrlContent image_;
    /// <summary>
    /// Optional input image to perform generations based on.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.ImageUrlContent Image {
      get { return image_; }
      set {
        image_ = value;
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 2;
    private string model_ = "";
    /// <summary>
    /// Name or alias of the image generation model to be used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "n" field.</summary>
    public const int NFieldNumber = 3;
    private readonly static int NDefaultValue = 0;

    private int n_;
    /// <summary>
    /// Number of images to generate. Allowed values are [1, 10].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int N {
      get { if ((_hasBits0 & 1) != 0) { return n_; } else { return NDefaultValue; } }
      set {
        _hasBits0 |= 1;
        n_ = value;
      }
    }
    /// <summary>Gets whether the "n" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasN {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "n" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearN() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 4;
    private string user_ = "";
    /// <summary>
    /// An opaque string supplied by the API client (customer) to identify a user.
    /// The string will be stored in the logs and can be used in customer service
    /// requests to identify certain requests.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "format" field.</summary>
    public const int FormatFieldNumber = 11;
    private global::XaiApi.ImageFormat format_ = global::XaiApi.ImageFormat.ImgFormatInvalid;
    /// <summary>
    /// Optional field to specify the image format to return the generated image(s)
    /// in. See ImageFormat enum for options.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.ImageFormat Format {
      get { return format_; }
      set {
        format_ = value;
      }
    }

    /// <summary>Field number for the "aspect_ratio" field.</summary>
    public const int AspectRatioFieldNumber = 14;
    private readonly static global::XaiApi.ImageAspectRatio AspectRatioDefaultValue = global::XaiApi.ImageAspectRatio.ImgAspectRatioInvalid;

    private global::XaiApi.ImageAspectRatio aspectRatio_;
    /// <summary>
    /// Optional aspect ratio for image generation/editing.
    /// Only supported by grok-imagine models.
    /// Defaults to 1:1 if not specified. Auto is only supported for image generation
    /// with a thinking upsampler.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.ImageAspectRatio AspectRatio {
      get { if ((_hasBits0 & 2) != 0) { return aspectRatio_; } else { return AspectRatioDefaultValue; } }
      set {
        _hasBits0 |= 2;
        aspectRatio_ = value;
      }
    }
    /// <summary>Gets whether the "aspect_ratio" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAspectRatio {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "aspect_ratio" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAspectRatio() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "resolution" field.</summary>
    public const int ResolutionFieldNumber = 15;
    private readonly static global::XaiApi.ImageResolution ResolutionDefaultValue = global::XaiApi.ImageResolution.ImgResolutionInvalid;

    private global::XaiApi.ImageResolution resolution_;
    /// <summary>
    /// Optional resolution for image generation/editing.
    /// Only supported by grok-imagine models.
    /// Defaults to 1k if not specified.
    /// When 2k is selected, the image is generated at 1k and upscaled using super-resolution.
    /// The final output area is capped at approximately 2048x2048 pixels, with dimensions
    /// adjusted to preserve aspect ratio and rounded to multiples of 16.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.ImageResolution Resolution {
      get { if ((_hasBits0 & 4) != 0) { return resolution_; } else { return ResolutionDefaultValue; } }
      set {
        _hasBits0 |= 4;
        resolution_ = value;
      }
    }
    /// <summary>Gets whether the "resolution" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResolution {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "resolution" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResolution() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateImageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateImageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Prompt != other.Prompt) return false;
      if (!object.Equals(Image, other.Image)) return false;
      if (Model != other.Model) return false;
      if (N != other.N) return false;
      if (User != other.User) return false;
      if (Format != other.Format) return false;
      if (AspectRatio != other.AspectRatio) return false;
      if (Resolution != other.Resolution) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Prompt.Length != 0) hash ^= Prompt.GetHashCode();
      if (image_ != null) hash ^= Image.GetHashCode();
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (HasN) hash ^= N.GetHashCode();
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Format != global::XaiApi.ImageFormat.ImgFormatInvalid) hash ^= Format.GetHashCode();
      if (HasAspectRatio) hash ^= AspectRatio.GetHashCode();
      if (HasResolution) hash ^= Resolution.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Prompt.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Prompt);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Model);
      }
      if (HasN) {
        output.WriteRawTag(24);
        output.WriteInt32(N);
      }
      if (User.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(User);
      }
      if (image_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Image);
      }
      if (Format != global::XaiApi.ImageFormat.ImgFormatInvalid) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Format);
      }
      if (HasAspectRatio) {
        output.WriteRawTag(112);
        output.WriteEnum((int) AspectRatio);
      }
      if (HasResolution) {
        output.WriteRawTag(120);
        output.WriteEnum((int) Resolution);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Prompt.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Prompt);
      }
      if (Model.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Model);
      }
      if (HasN) {
        output.WriteRawTag(24);
        output.WriteInt32(N);
      }
      if (User.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(User);
      }
      if (image_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Image);
      }
      if (Format != global::XaiApi.ImageFormat.ImgFormatInvalid) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Format);
      }
      if (HasAspectRatio) {
        output.WriteRawTag(112);
        output.WriteEnum((int) AspectRatio);
      }
      if (HasResolution) {
        output.WriteRawTag(120);
        output.WriteEnum((int) Resolution);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Prompt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prompt);
      }
      if (image_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Image);
      }
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (HasN) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(N);
      }
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Format != global::XaiApi.ImageFormat.ImgFormatInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Format);
      }
      if (HasAspectRatio) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AspectRatio);
      }
      if (HasResolution) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Resolution);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateImageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Prompt.Length != 0) {
        Prompt = other.Prompt;
      }
      if (other.image_ != null) {
        if (image_ == null) {
          Image = new global::XaiApi.ImageUrlContent();
        }
        Image.MergeFrom(other.Image);
      }
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.HasN) {
        N = other.N;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Format != global::XaiApi.ImageFormat.ImgFormatInvalid) {
        Format = other.Format;
      }
      if (other.HasAspectRatio) {
        AspectRatio = other.AspectRatio;
      }
      if (other.HasResolution) {
        Resolution = other.Resolution;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Prompt = input.ReadString();
            break;
          }
          case 18: {
            Model = input.ReadString();
            break;
          }
          case 24: {
            N = input.ReadInt32();
            break;
          }
          case 34: {
            User = input.ReadString();
            break;
          }
          case 42: {
            if (image_ == null) {
              Image = new global::XaiApi.ImageUrlContent();
            }
            input.ReadMessage(Image);
            break;
          }
          case 88: {
            Format = (global::XaiApi.ImageFormat) input.ReadEnum();
            break;
          }
          case 112: {
            AspectRatio = (global::XaiApi.ImageAspectRatio) input.ReadEnum();
            break;
          }
          case 120: {
            Resolution = (global::XaiApi.ImageResolution) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Prompt = input.ReadString();
            break;
          }
          case 18: {
            Model = input.ReadString();
            break;
          }
          case 24: {
            N = input.ReadInt32();
            break;
          }
          case 34: {
            User = input.ReadString();
            break;
          }
          case 42: {
            if (image_ == null) {
              Image = new global::XaiApi.ImageUrlContent();
            }
            input.ReadMessage(Image);
            break;
          }
          case 88: {
            Format = (global::XaiApi.ImageFormat) input.ReadEnum();
            break;
          }
          case 112: {
            AspectRatio = (global::XaiApi.ImageAspectRatio) input.ReadEnum();
            break;
          }
          case 120: {
            Resolution = (global::XaiApi.ImageResolution) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response from the image generation models containing the generated image(s).
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImageResponse : pb::IMessage<ImageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageResponse> _parser = new pb::MessageParser<ImageResponse>(() => new ImageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.ImageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse(ImageResponse other) : this() {
      images_ = other.images_.Clone();
      model_ = other.model_;
      usage_ = other.usage_ != null ? other.usage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse Clone() {
      return new ImageResponse(this);
    }

    /// <summary>Field number for the "images" field.</summary>
    public const int ImagesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XaiApi.GeneratedImage> _repeated_images_codec
        = pb::FieldCodec.ForMessage(10, global::XaiApi.GeneratedImage.Parser);
    private readonly pbc::RepeatedField<global::XaiApi.GeneratedImage> images_ = new pbc::RepeatedField<global::XaiApi.GeneratedImage>();
    /// <summary>
    /// A list of generated images (including relevant metadata).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::XaiApi.GeneratedImage> Images {
      get { return images_; }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 2;
    private string model_ = "";
    /// <summary>
    /// The model used to generate the image (ignoring aliases).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Model {
      get { return model_; }
      set {
        model_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usage" field.</summary>
    public const int UsageFieldNumber = 3;
    private global::XaiApi.SamplingUsage usage_;
    /// <summary>
    /// The usage of the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.SamplingUsage Usage {
      get { return usage_; }
      set {
        usage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!images_.Equals(other.images_)) return false;
      if (Model != other.Model) return false;
      if (!object.Equals(Usage, other.Usage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= images_.GetHashCode();
      if (Model.Length != 0) hash ^= Model.GetHashCode();
      if (usage_ != null) hash ^= Usage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      images_.WriteTo(output, _repeated_images_codec);
      if (Model.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Model);
      }
      if (usage_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Usage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      images_.WriteTo(ref output, _repeated_images_codec);
      if (Model.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Model);
      }
      if (usage_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Usage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += images_.CalculateSize(_repeated_images_codec);
      if (Model.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Model);
      }
      if (usage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Usage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageResponse other) {
      if (other == null) {
        return;
      }
      images_.Add(other.images_);
      if (other.Model.Length != 0) {
        Model = other.Model;
      }
      if (other.usage_ != null) {
        if (usage_ == null) {
          Usage = new global::XaiApi.SamplingUsage();
        }
        Usage.MergeFrom(other.Usage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            images_.AddEntriesFrom(input, _repeated_images_codec);
            break;
          }
          case 18: {
            Model = input.ReadString();
            break;
          }
          case 26: {
            if (usage_ == null) {
              Usage = new global::XaiApi.SamplingUsage();
            }
            input.ReadMessage(Usage);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            images_.AddEntriesFrom(ref input, _repeated_images_codec);
            break;
          }
          case 18: {
            Model = input.ReadString();
            break;
          }
          case 26: {
            if (usage_ == null) {
              Usage = new global::XaiApi.SamplingUsage();
            }
            input.ReadMessage(Usage);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Contains all data related to a generated image.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GeneratedImage : pb::IMessage<GeneratedImage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GeneratedImage> _parser = new pb::MessageParser<GeneratedImage>(() => new GeneratedImage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GeneratedImage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.ImageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratedImage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratedImage(GeneratedImage other) : this() {
      respectModeration_ = other.respectModeration_;
      switch (other.ImageCase) {
        case ImageOneofCase.Base64:
          Base64 = other.Base64;
          break;
        case ImageOneofCase.Url:
          Url = other.Url;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratedImage Clone() {
      return new GeneratedImage(this);
    }

    /// <summary>Field number for the "base64" field.</summary>
    public const int Base64FieldNumber = 1;
    /// <summary>
    /// A base-64 encoded string of the image. Provided if user specified `IMG_FORMAT_BASE64` in `format` field of the
    /// `GenerateImageRequest` message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Base64 {
      get { return HasBase64 ? (string) image_ : ""; }
      set {
        image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        imageCase_ = ImageOneofCase.Base64;
      }
    }
    /// <summary>Gets whether the "base64" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBase64 {
      get { return imageCase_ == ImageOneofCase.Base64; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "base64" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBase64() {
      if (HasBase64) {
        ClearImage();
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 3;
    /// <summary>
    /// A url that points to the generated image. Provided if user specified `IMG_FORMAT_URL` in `format` field of the
    /// `GenerateImageRequest` message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return HasUrl ? (string) image_ : ""; }
      set {
        image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        imageCase_ = ImageOneofCase.Url;
      }
    }
    /// <summary>Gets whether the "url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUrl {
      get { return imageCase_ == ImageOneofCase.Url; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "url" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUrl() {
      if (HasUrl) {
        ClearImage();
      }
    }

    /// <summary>Field number for the "respect_moderation" field.</summary>
    public const int RespectModerationFieldNumber = 4;
    private bool respectModeration_;
    /// <summary>
    /// Whether the image generated by the model respects moderation rules.
    /// The field will be true if the image respect moderation rules. Otherwise
    /// the field will be false and the image field is replaced by a placeholder.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RespectModeration {
      get { return respectModeration_; }
      set {
        respectModeration_ = value;
      }
    }

    private object image_;
    /// <summary>Enum of possible cases for the "image" oneof.</summary>
    public enum ImageOneofCase {
      None = 0,
      Base64 = 1,
      Url = 3,
    }
    private ImageOneofCase imageCase_ = ImageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageOneofCase ImageCase {
      get { return imageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearImage() {
      imageCase_ = ImageOneofCase.None;
      image_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GeneratedImage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GeneratedImage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Base64 != other.Base64) return false;
      if (Url != other.Url) return false;
      if (RespectModeration != other.RespectModeration) return false;
      if (ImageCase != other.ImageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBase64) hash ^= Base64.GetHashCode();
      if (HasUrl) hash ^= Url.GetHashCode();
      if (RespectModeration != false) hash ^= RespectModeration.GetHashCode();
      hash ^= (int) imageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBase64) {
        output.WriteRawTag(10);
        output.WriteString(Base64);
      }
      if (HasUrl) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (RespectModeration != false) {
        output.WriteRawTag(32);
        output.WriteBool(RespectModeration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBase64) {
        output.WriteRawTag(10);
        output.WriteString(Base64);
      }
      if (HasUrl) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (RespectModeration != false) {
        output.WriteRawTag(32);
        output.WriteBool(RespectModeration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBase64) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Base64);
      }
      if (HasUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (RespectModeration != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GeneratedImage other) {
      if (other == null) {
        return;
      }
      if (other.RespectModeration != false) {
        RespectModeration = other.RespectModeration;
      }
      switch (other.ImageCase) {
        case ImageOneofCase.Base64:
          Base64 = other.Base64;
          break;
        case ImageOneofCase.Url:
          Url = other.Url;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Base64 = input.ReadString();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 32: {
            RespectModeration = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Base64 = input.ReadString();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 32: {
            RespectModeration = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Contains data relating to an image that is provided to the model.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImageUrlContent : pb::IMessage<ImageUrlContent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageUrlContent> _parser = new pb::MessageParser<ImageUrlContent>(() => new ImageUrlContent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageUrlContent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.ImageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageUrlContent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageUrlContent(ImageUrlContent other) : this() {
      imageUrl_ = other.imageUrl_;
      detail_ = other.detail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageUrlContent Clone() {
      return new ImageUrlContent(this);
    }

    /// <summary>Field number for the "image_url" field.</summary>
    public const int ImageUrlFieldNumber = 1;
    private string imageUrl_ = "";
    /// <summary>
    /// This is either an image URL or a base64-encoded version of the image.
    /// The following image formats are supported: PNG, JPG, and WebP.
    /// If an image URL is provided, the image will be downloaded for every API
    /// request without being cached. Images are fetched using
    /// "XaiImageApiFetch/1.0" user agent, and will timeout after 5 seconds.
    /// The image size is limited to 10 MiB. If the image download fails, the API
    /// request will fail as well.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "detail" field.</summary>
    public const int DetailFieldNumber = 2;
    private global::XaiApi.ImageDetail detail_ = global::XaiApi.ImageDetail.DetailInvalid;
    /// <summary>
    /// The level of pre-processing resolution that will be applied to the image.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::XaiApi.ImageDetail Detail {
      get { return detail_; }
      set {
        detail_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageUrlContent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageUrlContent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ImageUrl != other.ImageUrl) return false;
      if (Detail != other.Detail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (Detail != global::XaiApi.ImageDetail.DetailInvalid) hash ^= Detail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImageUrl);
      }
      if (Detail != global::XaiApi.ImageDetail.DetailInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Detail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImageUrl);
      }
      if (Detail != global::XaiApi.ImageDetail.DetailInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Detail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (Detail != global::XaiApi.ImageDetail.DetailInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Detail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageUrlContent other) {
      if (other == null) {
        return;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      if (other.Detail != global::XaiApi.ImageDetail.DetailInvalid) {
        Detail = other.Detail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ImageUrl = input.ReadString();
            break;
          }
          case 16: {
            Detail = (global::XaiApi.ImageDetail) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ImageUrl = input.ReadString();
            break;
          }
          case 16: {
            Detail = (global::XaiApi.ImageDetail) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
