// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xai/shared/billing/types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProdCharger {

  /// <summary>Holder for reflection information generated from xai/shared/billing/types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for xai/shared/billing/types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch54YWkvc2hhcmVkL2JpbGxpbmcvdHlwZXMucHJvdG8SDHByb2RfY2hhcmdl",
            "ciIYCgRDZW50EhAKA3ZhbBgBIAEoA1IDdmFsImcKElBheW1lbnRNZXRob2RU",
            "eXBlcxJRChRwYXltZW50X21ldGhvZF90eXBlcxgBIAMoDjIfLnByb2RfY2hh",
            "cmdlci5QYXltZW50TWV0aG9kVHlwZVIScGF5bWVudE1ldGhvZFR5cGVzIpoB",
            "CgdBZGRyZXNzEhQKBWxpbmUxGAogASgJUgVsaW5lMRIUCgVsaW5lMhgLIAEo",
            "CVIFbGluZTISEgoEY2l0eRgPIAEoCVIEY2l0eRIYCgdjb3VudHJ5GBQgASgJ",
            "Ugdjb3VudHJ5Eh8KC3Bvc3RhbF9jb2RlGB4gASgJUgpwb3N0YWxDb2RlEhQK",
            "BXN0YXRlGCggASgJUgVzdGF0ZSKnAQoLQmlsbGluZ0luZm8SEgoEbmFtZRgK",
            "IAEoCVIEbmFtZRIvCgdhZGRyZXNzGBQgASgLMhUucHJvZF9jaGFyZ2VyLkFk",
            "ZHJlc3NSB2FkZHJlc3MSFAoFZW1haWwYHiABKAlSBWVtYWlsEh4KC3RheF9p",
            "ZF90eXBlGCggASgJUgl0YXhJZFR5cGUSHQoKdGF4X251bWJlchgpIAEoCVIJ",
            "dGF4TnVtYmVyInEKC0NhcmREZXRhaWxzEhQKBWJyYW5kGAogASgJUgVicmFu",
            "ZBIbCglleHBfbW9udGgYFCABKANSCGV4cE1vbnRoEhkKCGV4cF95ZWFyGB4g",
            "ASgDUgdleHBZZWFyEhQKBWxhc3Q0GCggASgJUgVsYXN0NCJcChRVc0JhbmtB",
            "Y2NvdW50QmxvY2tlZBIhCgxuZXR3b3JrX2NvZGUYCiABKAlSC25ldHdvcmtD",
            "b2RlEiEKDGJsb2NrX3JlYXNvbhgUIAEoCVILYmxvY2tSZWFzb24irgEKFFVz",
            "QmFua0FjY291bnREZXRhaWxzEhsKCWJhbmtfbmFtZRgKIAEoCVIIYmFua05h",
            "bWUSFAoFbGFzdDQYFCABKAlSBWxhc3Q0EiUKDnJvdXRpbmdfbnVtYmVyGB4g",
            "ASgJUg1yb3V0aW5nTnVtYmVyEjwKB2Jsb2NrZWQYKCABKAsyIi5wcm9kX2No",
            "YXJnZXIuVXNCYW5rQWNjb3VudEJsb2NrZWRSB2Jsb2NrZWQiIwoLTGlua0Rl",
            "dGFpbHMSFAoFZW1haWwYASABKAlSBWVtYWlsIvMCCg1QYXltZW50TWV0aG9k",
            "EioKEXBheW1lbnRfbWV0aG9kX2lkGAogASgJUg9wYXltZW50TWV0aG9kSWQS",
            "PAoMYmlsbGluZ19pbmZvGBQgASgLMhkucHJvZF9jaGFyZ2VyLkJpbGxpbmdJ",
            "bmZvUgtiaWxsaW5nSW5mbxI8CgxjYXJkX2RldGFpbHMYHiABKAsyGS5wcm9k",
            "X2NoYXJnZXIuQ2FyZERldGFpbHNSC2NhcmREZXRhaWxzElkKF3VzX2Jhbmtf",
            "YWNjb3VudF9kZXRhaWxzGB8gASgLMiIucHJvZF9jaGFyZ2VyLlVzQmFua0Fj",
            "Y291bnREZXRhaWxzUhR1c0JhbmtBY2NvdW50RGV0YWlscxI8CgxsaW5rX2Rl",
            "dGFpbHMYICABKAsyGS5wcm9kX2NoYXJnZXIuTGlua0RldGFpbHNSC2xpbmtE",
            "ZXRhaWxzEiEKDHBheW1lbnRfdHlwZRgoIAEoCVILcGF5bWVudFR5cGUqWgoR",
            "UGF5bWVudE1ldGhvZFR5cGUSDwoLVU5LTk9XTl9QTVQQABIICgRDQVJEEAoS",
            "CwoHQ0FTSEFQUBAUEggKBExJTksQHhITCg9VU19CQU5LX0FDQ09VTlQQKEJq",
            "ChBjb20ucHJvZF9jaGFyZ2VyQgpUeXBlc1Byb3RvUAGiAgNQWFiqAgtQcm9k",
            "Q2hhcmdlcsoCC1Byb2RDaGFyZ2Vy4gIXUHJvZENoYXJnZXJcR1BCTWV0YWRh",
            "dGHqAgtQcm9kQ2hhcmdlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProdCharger.PaymentMethodType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.Cent), global::ProdCharger.Cent.Parser, new[]{ "Val" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.PaymentMethodTypes), global::ProdCharger.PaymentMethodTypes.Parser, new[]{ "PaymentMethodTypes_" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.Address), global::ProdCharger.Address.Parser, new[]{ "Line1", "Line2", "City", "Country", "PostalCode", "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.BillingInfo), global::ProdCharger.BillingInfo.Parser, new[]{ "Name", "Address", "Email", "TaxIdType", "TaxNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.CardDetails), global::ProdCharger.CardDetails.Parser, new[]{ "Brand", "ExpMonth", "ExpYear", "Last4" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.UsBankAccountBlocked), global::ProdCharger.UsBankAccountBlocked.Parser, new[]{ "NetworkCode", "BlockReason" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.UsBankAccountDetails), global::ProdCharger.UsBankAccountDetails.Parser, new[]{ "BankName", "Last4", "RoutingNumber", "Blocked" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.LinkDetails), global::ProdCharger.LinkDetails.Parser, new[]{ "Email" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProdCharger.PaymentMethod), global::ProdCharger.PaymentMethod.Parser, new[]{ "PaymentMethodId", "BillingInfo", "CardDetails", "UsBankAccountDetails", "LinkDetails", "PaymentType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Payment method types.
  /// </summary>
  public enum PaymentMethodType {
    [pbr::OriginalName("UNKNOWN_PMT")] UnknownPmt = 0,
    [pbr::OriginalName("CARD")] Card = 10,
    [pbr::OriginalName("CASHAPP")] Cashapp = 20,
    [pbr::OriginalName("LINK")] Link = 30,
    [pbr::OriginalName("US_BANK_ACCOUNT")] UsBankAccount = 40,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Representation of USD Cents.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Cent : pb::IMessage<Cent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cent> _parser = new pb::MessageParser<Cent>(() => new Cent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cent(Cent other) : this() {
      val_ = other.val_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cent Clone() {
      return new Cent(this);
    }

    /// <summary>Field number for the "val" field.</summary>
    public const int ValFieldNumber = 1;
    private long val_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Val {
      get { return val_; }
      set {
        val_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Val != other.Val) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Val != 0L) hash ^= Val.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Val != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Val);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Val != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Val);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Val != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Val);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cent other) {
      if (other == null) {
        return;
      }
      if (other.Val != 0L) {
        Val = other.Val;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Val = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Val = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Payment method types wrapper to allow repeated optional fields.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PaymentMethodTypes : pb::IMessage<PaymentMethodTypes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentMethodTypes> _parser = new pb::MessageParser<PaymentMethodTypes>(() => new PaymentMethodTypes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentMethodTypes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethodTypes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethodTypes(PaymentMethodTypes other) : this() {
      paymentMethodTypes_ = other.paymentMethodTypes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethodTypes Clone() {
      return new PaymentMethodTypes(this);
    }

    /// <summary>Field number for the "payment_method_types" field.</summary>
    public const int PaymentMethodTypes_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::ProdCharger.PaymentMethodType> _repeated_paymentMethodTypes_codec
        = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::ProdCharger.PaymentMethodType) x);
    private readonly pbc::RepeatedField<global::ProdCharger.PaymentMethodType> paymentMethodTypes_ = new pbc::RepeatedField<global::ProdCharger.PaymentMethodType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProdCharger.PaymentMethodType> PaymentMethodTypes_ {
      get { return paymentMethodTypes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentMethodTypes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentMethodTypes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!paymentMethodTypes_.Equals(other.paymentMethodTypes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= paymentMethodTypes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      paymentMethodTypes_.WriteTo(output, _repeated_paymentMethodTypes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      paymentMethodTypes_.WriteTo(ref output, _repeated_paymentMethodTypes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += paymentMethodTypes_.CalculateSize(_repeated_paymentMethodTypes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentMethodTypes other) {
      if (other == null) {
        return;
      }
      paymentMethodTypes_.Add(other.paymentMethodTypes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            paymentMethodTypes_.AddEntriesFrom(input, _repeated_paymentMethodTypes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            paymentMethodTypes_.AddEntriesFrom(ref input, _repeated_paymentMethodTypes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A redacted version of card details. The actual card details are handled by third-party payment providers.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Address : pb::IMessage<Address>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address(Address other) : this() {
      line1_ = other.line1_;
      line2_ = other.line2_;
      city_ = other.city_;
      country_ = other.country_;
      postalCode_ = other.postalCode_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "line1" field.</summary>
    public const int Line1FieldNumber = 10;
    private string line1_ = "";
    /// <summary>
    /// Address line 1 (e.g., street, PO Box, or company name).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Line1 {
      get { return line1_; }
      set {
        line1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "line2" field.</summary>
    public const int Line2FieldNumber = 11;
    private string line2_ = "";
    /// <summary>
    /// Address line 2 (e.g., apartment, suite, unit, or building).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Line2 {
      get { return line2_; }
      set {
        line2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 15;
    private string city_ = "";
    /// <summary>
    /// City, district, suburb, town, or village.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string City {
      get { return city_; }
      set {
        city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 20;
    private string country_ = "";
    /// <summary>
    /// Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "postal_code" field.</summary>
    public const int PostalCodeFieldNumber = 30;
    private string postalCode_ = "";
    /// <summary>
    /// ZIP or postal code.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PostalCode {
      get { return postalCode_; }
      set {
        postalCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 40;
    private string state_ = "";
    /// <summary>
    /// State, county, province, or region.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string State {
      get { return state_; }
      set {
        state_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Line1 != other.Line1) return false;
      if (Line2 != other.Line2) return false;
      if (City != other.City) return false;
      if (Country != other.Country) return false;
      if (PostalCode != other.PostalCode) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Line1.Length != 0) hash ^= Line1.GetHashCode();
      if (Line2.Length != 0) hash ^= Line2.GetHashCode();
      if (City.Length != 0) hash ^= City.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (PostalCode.Length != 0) hash ^= PostalCode.GetHashCode();
      if (State.Length != 0) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Line1.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Line1);
      }
      if (Line2.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Line2);
      }
      if (City.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(City);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Country);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(PostalCode);
      }
      if (State.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Line1.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Line1);
      }
      if (Line2.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Line2);
      }
      if (City.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(City);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Country);
      }
      if (PostalCode.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(PostalCode);
      }
      if (State.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Line1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Line1);
      }
      if (Line2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Line2);
      }
      if (City.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
      }
      if (Country.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (PostalCode.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PostalCode);
      }
      if (State.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.Line1.Length != 0) {
        Line1 = other.Line1;
      }
      if (other.Line2.Length != 0) {
        Line2 = other.Line2;
      }
      if (other.City.Length != 0) {
        City = other.City;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.PostalCode.Length != 0) {
        PostalCode = other.PostalCode;
      }
      if (other.State.Length != 0) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            Line1 = input.ReadString();
            break;
          }
          case 90: {
            Line2 = input.ReadString();
            break;
          }
          case 122: {
            City = input.ReadString();
            break;
          }
          case 162: {
            Country = input.ReadString();
            break;
          }
          case 242: {
            PostalCode = input.ReadString();
            break;
          }
          case 322: {
            State = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            Line1 = input.ReadString();
            break;
          }
          case 90: {
            Line2 = input.ReadString();
            break;
          }
          case 122: {
            City = input.ReadString();
            break;
          }
          case 162: {
            Country = input.ReadString();
            break;
          }
          case 242: {
            PostalCode = input.ReadString();
            break;
          }
          case 322: {
            State = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Billing info.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BillingInfo : pb::IMessage<BillingInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BillingInfo> _parser = new pb::MessageParser<BillingInfo>(() => new BillingInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BillingInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BillingInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BillingInfo(BillingInfo other) : this() {
      name_ = other.name_;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      email_ = other.email_;
      taxIdType_ = other.taxIdType_;
      taxNumber_ = other.taxNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BillingInfo Clone() {
      return new BillingInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 10;
    private string name_ = "";
    /// <summary>
    /// The customer's full name or business name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 20;
    private global::ProdCharger.Address address_;
    /// <summary>
    /// The customer's address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.Address Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 30;
    private string email_ = "";
    /// <summary>
    /// The customer's email.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tax_id_type" field.</summary>
    public const int TaxIdTypeFieldNumber = 40;
    private string taxIdType_ = "";
    /// <summary>
    /// Customer Tax ID type on Stripe ([Stripe Reference](https://docs.stripe.com/api/tax_ids/customer_create))
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxIdType {
      get { return taxIdType_; }
      set {
        taxIdType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tax_number" field.</summary>
    public const int TaxNumberFieldNumber = 41;
    private string taxNumber_ = "";
    /// <summary>
    /// Customer Tax ID number on Stripe ([Stripe Reference](https://docs.stripe.com/api/tax_ids/customer_create))
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxNumber {
      get { return taxNumber_; }
      set {
        taxNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BillingInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BillingInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Address, other.Address)) return false;
      if (Email != other.Email) return false;
      if (TaxIdType != other.TaxIdType) return false;
      if (TaxNumber != other.TaxNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (TaxIdType.Length != 0) hash ^= TaxIdType.GetHashCode();
      if (TaxNumber.Length != 0) hash ^= TaxNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Name);
      }
      if (address_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(Address);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Email);
      }
      if (TaxIdType.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(TaxIdType);
      }
      if (TaxNumber.Length != 0) {
        output.WriteRawTag(202, 2);
        output.WriteString(TaxNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Name);
      }
      if (address_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(Address);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(Email);
      }
      if (TaxIdType.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(TaxIdType);
      }
      if (TaxNumber.Length != 0) {
        output.WriteRawTag(202, 2);
        output.WriteString(TaxNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (address_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (Email.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (TaxIdType.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TaxIdType);
      }
      if (TaxNumber.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TaxNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BillingInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::ProdCharger.Address();
        }
        Address.MergeFrom(other.Address);
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.TaxIdType.Length != 0) {
        TaxIdType = other.TaxIdType;
      }
      if (other.TaxNumber.Length != 0) {
        TaxNumber = other.TaxNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            Name = input.ReadString();
            break;
          }
          case 162: {
            if (address_ == null) {
              Address = new global::ProdCharger.Address();
            }
            input.ReadMessage(Address);
            break;
          }
          case 242: {
            Email = input.ReadString();
            break;
          }
          case 322: {
            TaxIdType = input.ReadString();
            break;
          }
          case 330: {
            TaxNumber = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            Name = input.ReadString();
            break;
          }
          case 162: {
            if (address_ == null) {
              Address = new global::ProdCharger.Address();
            }
            input.ReadMessage(Address);
            break;
          }
          case 242: {
            Email = input.ReadString();
            break;
          }
          case 322: {
            TaxIdType = input.ReadString();
            break;
          }
          case 330: {
            TaxNumber = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// A redacted version of card details. The actual card details are handled by third-party payment providers.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CardDetails : pb::IMessage<CardDetails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CardDetails> _parser = new pb::MessageParser<CardDetails>(() => new CardDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CardDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardDetails(CardDetails other) : this() {
      brand_ = other.brand_;
      expMonth_ = other.expMonth_;
      expYear_ = other.expYear_;
      last4_ = other.last4_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CardDetails Clone() {
      return new CardDetails(this);
    }

    /// <summary>Field number for the "brand" field.</summary>
    public const int BrandFieldNumber = 10;
    private string brand_ = "";
    /// <summary>
    /// Card brand.
    /// Can be `amex`, `diners`, `discover`, `eftpos_au`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Brand {
      get { return brand_; }
      set {
        brand_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exp_month" field.</summary>
    public const int ExpMonthFieldNumber = 20;
    private long expMonth_;
    /// <summary>
    /// Two-digit number representing the card's expiration month.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpMonth {
      get { return expMonth_; }
      set {
        expMonth_ = value;
      }
    }

    /// <summary>Field number for the "exp_year" field.</summary>
    public const int ExpYearFieldNumber = 30;
    private long expYear_;
    /// <summary>
    /// Four-digit number representing the card's expiration year.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpYear {
      get { return expYear_; }
      set {
        expYear_ = value;
      }
    }

    /// <summary>Field number for the "last4" field.</summary>
    public const int Last4FieldNumber = 40;
    private string last4_ = "";
    /// <summary>
    /// The last four digits of the card.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Last4 {
      get { return last4_; }
      set {
        last4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CardDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CardDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Brand != other.Brand) return false;
      if (ExpMonth != other.ExpMonth) return false;
      if (ExpYear != other.ExpYear) return false;
      if (Last4 != other.Last4) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Brand.Length != 0) hash ^= Brand.GetHashCode();
      if (ExpMonth != 0L) hash ^= ExpMonth.GetHashCode();
      if (ExpYear != 0L) hash ^= ExpYear.GetHashCode();
      if (Last4.Length != 0) hash ^= Last4.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Brand.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Brand);
      }
      if (ExpMonth != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(ExpMonth);
      }
      if (ExpYear != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(ExpYear);
      }
      if (Last4.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(Last4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Brand.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Brand);
      }
      if (ExpMonth != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(ExpMonth);
      }
      if (ExpYear != 0L) {
        output.WriteRawTag(240, 1);
        output.WriteInt64(ExpYear);
      }
      if (Last4.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(Last4);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Brand.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Brand);
      }
      if (ExpMonth != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ExpMonth);
      }
      if (ExpYear != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(ExpYear);
      }
      if (Last4.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Last4);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CardDetails other) {
      if (other == null) {
        return;
      }
      if (other.Brand.Length != 0) {
        Brand = other.Brand;
      }
      if (other.ExpMonth != 0L) {
        ExpMonth = other.ExpMonth;
      }
      if (other.ExpYear != 0L) {
        ExpYear = other.ExpYear;
      }
      if (other.Last4.Length != 0) {
        Last4 = other.Last4;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            Brand = input.ReadString();
            break;
          }
          case 160: {
            ExpMonth = input.ReadInt64();
            break;
          }
          case 240: {
            ExpYear = input.ReadInt64();
            break;
          }
          case 322: {
            Last4 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            Brand = input.ReadString();
            break;
          }
          case 160: {
            ExpMonth = input.ReadInt64();
            break;
          }
          case 240: {
            ExpYear = input.ReadInt64();
            break;
          }
          case 322: {
            Last4 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ACH blocked reason.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UsBankAccountBlocked : pb::IMessage<UsBankAccountBlocked>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsBankAccountBlocked> _parser = new pb::MessageParser<UsBankAccountBlocked>(() => new UsBankAccountBlocked());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UsBankAccountBlocked> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountBlocked() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountBlocked(UsBankAccountBlocked other) : this() {
      networkCode_ = other.networkCode_;
      blockReason_ = other.blockReason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountBlocked Clone() {
      return new UsBankAccountBlocked(this);
    }

    /// <summary>Field number for the "network_code" field.</summary>
    public const int NetworkCodeFieldNumber = 10;
    private string networkCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NetworkCode {
      get { return networkCode_; }
      set {
        networkCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "block_reason" field.</summary>
    public const int BlockReasonFieldNumber = 20;
    private string blockReason_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BlockReason {
      get { return blockReason_; }
      set {
        blockReason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UsBankAccountBlocked);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UsBankAccountBlocked other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NetworkCode != other.NetworkCode) return false;
      if (BlockReason != other.BlockReason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NetworkCode.Length != 0) hash ^= NetworkCode.GetHashCode();
      if (BlockReason.Length != 0) hash ^= BlockReason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NetworkCode.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(NetworkCode);
      }
      if (BlockReason.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(BlockReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NetworkCode.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(NetworkCode);
      }
      if (BlockReason.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(BlockReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NetworkCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NetworkCode);
      }
      if (BlockReason.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(BlockReason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UsBankAccountBlocked other) {
      if (other == null) {
        return;
      }
      if (other.NetworkCode.Length != 0) {
        NetworkCode = other.NetworkCode;
      }
      if (other.BlockReason.Length != 0) {
        BlockReason = other.BlockReason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            NetworkCode = input.ReadString();
            break;
          }
          case 162: {
            BlockReason = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            NetworkCode = input.ReadString();
            break;
          }
          case 162: {
            BlockReason = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// ACH details.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UsBankAccountDetails : pb::IMessage<UsBankAccountDetails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsBankAccountDetails> _parser = new pb::MessageParser<UsBankAccountDetails>(() => new UsBankAccountDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UsBankAccountDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountDetails(UsBankAccountDetails other) : this() {
      bankName_ = other.bankName_;
      last4_ = other.last4_;
      routingNumber_ = other.routingNumber_;
      blocked_ = other.blocked_ != null ? other.blocked_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UsBankAccountDetails Clone() {
      return new UsBankAccountDetails(this);
    }

    /// <summary>Field number for the "bank_name" field.</summary>
    public const int BankNameFieldNumber = 10;
    private string bankName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BankName {
      get { return bankName_; }
      set {
        bankName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last4" field.</summary>
    public const int Last4FieldNumber = 20;
    private string last4_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Last4 {
      get { return last4_; }
      set {
        last4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "routing_number" field.</summary>
    public const int RoutingNumberFieldNumber = 30;
    private string routingNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RoutingNumber {
      get { return routingNumber_; }
      set {
        routingNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "blocked" field.</summary>
    public const int BlockedFieldNumber = 40;
    private global::ProdCharger.UsBankAccountBlocked blocked_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.UsBankAccountBlocked Blocked {
      get { return blocked_; }
      set {
        blocked_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UsBankAccountDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UsBankAccountDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BankName != other.BankName) return false;
      if (Last4 != other.Last4) return false;
      if (RoutingNumber != other.RoutingNumber) return false;
      if (!object.Equals(Blocked, other.Blocked)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BankName.Length != 0) hash ^= BankName.GetHashCode();
      if (Last4.Length != 0) hash ^= Last4.GetHashCode();
      if (RoutingNumber.Length != 0) hash ^= RoutingNumber.GetHashCode();
      if (blocked_ != null) hash ^= Blocked.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BankName.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(BankName);
      }
      if (Last4.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Last4);
      }
      if (RoutingNumber.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(RoutingNumber);
      }
      if (blocked_ != null) {
        output.WriteRawTag(194, 2);
        output.WriteMessage(Blocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BankName.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(BankName);
      }
      if (Last4.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(Last4);
      }
      if (RoutingNumber.Length != 0) {
        output.WriteRawTag(242, 1);
        output.WriteString(RoutingNumber);
      }
      if (blocked_ != null) {
        output.WriteRawTag(194, 2);
        output.WriteMessage(Blocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BankName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankName);
      }
      if (Last4.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Last4);
      }
      if (RoutingNumber.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(RoutingNumber);
      }
      if (blocked_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Blocked);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UsBankAccountDetails other) {
      if (other == null) {
        return;
      }
      if (other.BankName.Length != 0) {
        BankName = other.BankName;
      }
      if (other.Last4.Length != 0) {
        Last4 = other.Last4;
      }
      if (other.RoutingNumber.Length != 0) {
        RoutingNumber = other.RoutingNumber;
      }
      if (other.blocked_ != null) {
        if (blocked_ == null) {
          Blocked = new global::ProdCharger.UsBankAccountBlocked();
        }
        Blocked.MergeFrom(other.Blocked);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            BankName = input.ReadString();
            break;
          }
          case 162: {
            Last4 = input.ReadString();
            break;
          }
          case 242: {
            RoutingNumber = input.ReadString();
            break;
          }
          case 322: {
            if (blocked_ == null) {
              Blocked = new global::ProdCharger.UsBankAccountBlocked();
            }
            input.ReadMessage(Blocked);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            BankName = input.ReadString();
            break;
          }
          case 162: {
            Last4 = input.ReadString();
            break;
          }
          case 242: {
            RoutingNumber = input.ReadString();
            break;
          }
          case 322: {
            if (blocked_ == null) {
              Blocked = new global::ProdCharger.UsBankAccountBlocked();
            }
            input.ReadMessage(Blocked);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Link payment details.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LinkDetails : pb::IMessage<LinkDetails>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LinkDetails> _parser = new pb::MessageParser<LinkDetails>(() => new LinkDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LinkDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkDetails(LinkDetails other) : this() {
      email_ = other.email_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkDetails Clone() {
      return new LinkDetails(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LinkDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LinkDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LinkDetails other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Payment method and details.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PaymentMethod : pb::IMessage<PaymentMethod>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentMethod> _parser = new pb::MessageParser<PaymentMethod>(() => new PaymentMethod());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentMethod> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProdCharger.TypesReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethod() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethod(PaymentMethod other) : this() {
      paymentMethodId_ = other.paymentMethodId_;
      billingInfo_ = other.billingInfo_ != null ? other.billingInfo_.Clone() : null;
      cardDetails_ = other.cardDetails_ != null ? other.cardDetails_.Clone() : null;
      usBankAccountDetails_ = other.usBankAccountDetails_ != null ? other.usBankAccountDetails_.Clone() : null;
      linkDetails_ = other.linkDetails_ != null ? other.linkDetails_.Clone() : null;
      paymentType_ = other.paymentType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentMethod Clone() {
      return new PaymentMethod(this);
    }

    /// <summary>Field number for the "payment_method_id" field.</summary>
    public const int PaymentMethodIdFieldNumber = 10;
    private string paymentMethodId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentMethodId {
      get { return paymentMethodId_; }
      set {
        paymentMethodId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "billing_info" field.</summary>
    public const int BillingInfoFieldNumber = 20;
    private global::ProdCharger.BillingInfo billingInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.BillingInfo BillingInfo {
      get { return billingInfo_; }
      set {
        billingInfo_ = value;
      }
    }

    /// <summary>Field number for the "card_details" field.</summary>
    public const int CardDetailsFieldNumber = 30;
    private global::ProdCharger.CardDetails cardDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.CardDetails CardDetails {
      get { return cardDetails_; }
      set {
        cardDetails_ = value;
      }
    }

    /// <summary>Field number for the "us_bank_account_details" field.</summary>
    public const int UsBankAccountDetailsFieldNumber = 31;
    private global::ProdCharger.UsBankAccountDetails usBankAccountDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.UsBankAccountDetails UsBankAccountDetails {
      get { return usBankAccountDetails_; }
      set {
        usBankAccountDetails_ = value;
      }
    }

    /// <summary>Field number for the "link_details" field.</summary>
    public const int LinkDetailsFieldNumber = 32;
    private global::ProdCharger.LinkDetails linkDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProdCharger.LinkDetails LinkDetails {
      get { return linkDetails_; }
      set {
        linkDetails_ = value;
      }
    }

    /// <summary>Field number for the "payment_type" field.</summary>
    public const int PaymentTypeFieldNumber = 40;
    private string paymentType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentType {
      get { return paymentType_; }
      set {
        paymentType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentMethod);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentMethod other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentMethodId != other.PaymentMethodId) return false;
      if (!object.Equals(BillingInfo, other.BillingInfo)) return false;
      if (!object.Equals(CardDetails, other.CardDetails)) return false;
      if (!object.Equals(UsBankAccountDetails, other.UsBankAccountDetails)) return false;
      if (!object.Equals(LinkDetails, other.LinkDetails)) return false;
      if (PaymentType != other.PaymentType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentMethodId.Length != 0) hash ^= PaymentMethodId.GetHashCode();
      if (billingInfo_ != null) hash ^= BillingInfo.GetHashCode();
      if (cardDetails_ != null) hash ^= CardDetails.GetHashCode();
      if (usBankAccountDetails_ != null) hash ^= UsBankAccountDetails.GetHashCode();
      if (linkDetails_ != null) hash ^= LinkDetails.GetHashCode();
      if (PaymentType.Length != 0) hash ^= PaymentType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentMethodId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PaymentMethodId);
      }
      if (billingInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(BillingInfo);
      }
      if (cardDetails_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(CardDetails);
      }
      if (usBankAccountDetails_ != null) {
        output.WriteRawTag(250, 1);
        output.WriteMessage(UsBankAccountDetails);
      }
      if (linkDetails_ != null) {
        output.WriteRawTag(130, 2);
        output.WriteMessage(LinkDetails);
      }
      if (PaymentType.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(PaymentType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentMethodId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PaymentMethodId);
      }
      if (billingInfo_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(BillingInfo);
      }
      if (cardDetails_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(CardDetails);
      }
      if (usBankAccountDetails_ != null) {
        output.WriteRawTag(250, 1);
        output.WriteMessage(UsBankAccountDetails);
      }
      if (linkDetails_ != null) {
        output.WriteRawTag(130, 2);
        output.WriteMessage(LinkDetails);
      }
      if (PaymentType.Length != 0) {
        output.WriteRawTag(194, 2);
        output.WriteString(PaymentType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentMethodId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentMethodId);
      }
      if (billingInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BillingInfo);
      }
      if (cardDetails_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CardDetails);
      }
      if (usBankAccountDetails_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(UsBankAccountDetails);
      }
      if (linkDetails_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LinkDetails);
      }
      if (PaymentType.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PaymentType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentMethod other) {
      if (other == null) {
        return;
      }
      if (other.PaymentMethodId.Length != 0) {
        PaymentMethodId = other.PaymentMethodId;
      }
      if (other.billingInfo_ != null) {
        if (billingInfo_ == null) {
          BillingInfo = new global::ProdCharger.BillingInfo();
        }
        BillingInfo.MergeFrom(other.BillingInfo);
      }
      if (other.cardDetails_ != null) {
        if (cardDetails_ == null) {
          CardDetails = new global::ProdCharger.CardDetails();
        }
        CardDetails.MergeFrom(other.CardDetails);
      }
      if (other.usBankAccountDetails_ != null) {
        if (usBankAccountDetails_ == null) {
          UsBankAccountDetails = new global::ProdCharger.UsBankAccountDetails();
        }
        UsBankAccountDetails.MergeFrom(other.UsBankAccountDetails);
      }
      if (other.linkDetails_ != null) {
        if (linkDetails_ == null) {
          LinkDetails = new global::ProdCharger.LinkDetails();
        }
        LinkDetails.MergeFrom(other.LinkDetails);
      }
      if (other.PaymentType.Length != 0) {
        PaymentType = other.PaymentType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            PaymentMethodId = input.ReadString();
            break;
          }
          case 162: {
            if (billingInfo_ == null) {
              BillingInfo = new global::ProdCharger.BillingInfo();
            }
            input.ReadMessage(BillingInfo);
            break;
          }
          case 242: {
            if (cardDetails_ == null) {
              CardDetails = new global::ProdCharger.CardDetails();
            }
            input.ReadMessage(CardDetails);
            break;
          }
          case 250: {
            if (usBankAccountDetails_ == null) {
              UsBankAccountDetails = new global::ProdCharger.UsBankAccountDetails();
            }
            input.ReadMessage(UsBankAccountDetails);
            break;
          }
          case 258: {
            if (linkDetails_ == null) {
              LinkDetails = new global::ProdCharger.LinkDetails();
            }
            input.ReadMessage(LinkDetails);
            break;
          }
          case 322: {
            PaymentType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            PaymentMethodId = input.ReadString();
            break;
          }
          case 162: {
            if (billingInfo_ == null) {
              BillingInfo = new global::ProdCharger.BillingInfo();
            }
            input.ReadMessage(BillingInfo);
            break;
          }
          case 242: {
            if (cardDetails_ == null) {
              CardDetails = new global::ProdCharger.CardDetails();
            }
            input.ReadMessage(CardDetails);
            break;
          }
          case 250: {
            if (usBankAccountDetails_ == null) {
              UsBankAccountDetails = new global::ProdCharger.UsBankAccountDetails();
            }
            input.ReadMessage(UsBankAccountDetails);
            break;
          }
          case 258: {
            if (linkDetails_ == null) {
              LinkDetails = new global::ProdCharger.LinkDetails();
            }
            input.ReadMessage(LinkDetails);
            break;
          }
          case 322: {
            PaymentType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
