// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: xai/api/v1/usage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XaiApi {

  /// <summary>Holder for reflection information generated from xai/api/v1/usage.proto</summary>
  public static partial class UsageReflection {

    #region Descriptor
    /// <summary>File descriptor for xai/api/v1/usage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UsageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ4YWkvYXBpL3YxL3VzYWdlLnByb3RvEgd4YWlfYXBpIsADCg1TYW1wbGlu",
            "Z1VzYWdlEisKEWNvbXBsZXRpb25fdG9rZW5zGAEgASgFUhBjb21wbGV0aW9u",
            "VG9rZW5zEikKEHJlYXNvbmluZ190b2tlbnMYBiABKAVSD3JlYXNvbmluZ1Rv",
            "a2VucxIjCg1wcm9tcHRfdG9rZW5zGAIgASgFUgxwcm9tcHRUb2tlbnMSIQoM",
            "dG90YWxfdG9rZW5zGAMgASgFUgt0b3RhbFRva2VucxIsChJwcm9tcHRfdGV4",
            "dF90b2tlbnMYBCABKAVSEHByb21wdFRleHRUb2tlbnMSOQoZY2FjaGVkX3By",
            "b21wdF90ZXh0X3Rva2VucxgHIAEoBVIWY2FjaGVkUHJvbXB0VGV4dFRva2Vu",
            "cxIuChNwcm9tcHRfaW1hZ2VfdG9rZW5zGAUgASgFUhFwcm9tcHRJbWFnZVRv",
            "a2VucxIoChBudW1fc291cmNlc191c2VkGAggASgFUg5udW1Tb3VyY2VzVXNl",
            "ZBJMChZzZXJ2ZXJfc2lkZV90b29sc191c2VkGAkgAygOMhcueGFpX2FwaS5T",
            "ZXJ2ZXJTaWRlVG9vbFITc2VydmVyU2lkZVRvb2xzVXNlZCJyCg5FbWJlZGRp",
            "bmdVc2FnZRIuChNudW1fdGV4dF9lbWJlZGRpbmdzGAEgASgFUhFudW1UZXh0",
            "RW1iZWRkaW5ncxIwChRudW1faW1hZ2VfZW1iZWRkaW5ncxgCIAEoBVISbnVt",
            "SW1hZ2VFbWJlZGRpbmdzKsICCg5TZXJ2ZXJTaWRlVG9vbBIcChhTRVJWRVJf",
            "U0lERV9UT09MX0lOVkFMSUQQABIfChtTRVJWRVJfU0lERV9UT09MX1dFQl9T",
            "RUFSQ0gQARIdChlTRVJWRVJfU0lERV9UT09MX1hfU0VBUkNIEAISIwofU0VS",
            "VkVSX1NJREVfVE9PTF9DT0RFX0VYRUNVVElPThADEh8KG1NFUlZFUl9TSURF",
            "X1RPT0xfVklFV19JTUFHRRAEEiEKHVNFUlZFUl9TSURFX1RPT0xfVklFV19Y",
            "X1ZJREVPEAUSJwojU0VSVkVSX1NJREVfVE9PTF9DT0xMRUNUSU9OU19TRUFS",
            "Q0gQBhIYChRTRVJWRVJfU0lERV9UT09MX01DUBAHEiYKIlNFUlZFUl9TSURF",
            "X1RPT0xfQVRUQUNITUVOVF9TRUFSQ0gQCEJRCgtjb20ueGFpX2FwaUIKVXNh",
            "Z2VQcm90b1ABogIDWFhYqgIGWGFpQXBpygIGWGFpQXBp4gISWGFpQXBpXEdQ",
            "Qk1ldGFkYXRh6gIGWGFpQXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::XaiApi.ServerSideTool), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.SamplingUsage), global::XaiApi.SamplingUsage.Parser, new[]{ "CompletionTokens", "ReasoningTokens", "PromptTokens", "TotalTokens", "PromptTextTokens", "CachedPromptTextTokens", "PromptImageTokens", "NumSourcesUsed", "ServerSideToolsUsed" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XaiApi.EmbeddingUsage), global::XaiApi.EmbeddingUsage.Parser, new[]{ "NumTextEmbeddings", "NumImageEmbeddings" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ServerSideTool {
    [pbr::OriginalName("SERVER_SIDE_TOOL_INVALID")] Invalid = 0,
    [pbr::OriginalName("SERVER_SIDE_TOOL_WEB_SEARCH")] WebSearch = 1,
    [pbr::OriginalName("SERVER_SIDE_TOOL_X_SEARCH")] XSearch = 2,
    [pbr::OriginalName("SERVER_SIDE_TOOL_CODE_EXECUTION")] CodeExecution = 3,
    [pbr::OriginalName("SERVER_SIDE_TOOL_VIEW_IMAGE")] ViewImage = 4,
    [pbr::OriginalName("SERVER_SIDE_TOOL_VIEW_X_VIDEO")] ViewXVideo = 5,
    [pbr::OriginalName("SERVER_SIDE_TOOL_COLLECTIONS_SEARCH")] CollectionsSearch = 6,
    [pbr::OriginalName("SERVER_SIDE_TOOL_MCP")] Mcp = 7,
    [pbr::OriginalName("SERVER_SIDE_TOOL_ATTACHMENT_SEARCH")] AttachmentSearch = 8,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Records the cost associated with a sampling request (both chat and sample
  /// endpoints).
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SamplingUsage : pb::IMessage<SamplingUsage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SamplingUsage> _parser = new pb::MessageParser<SamplingUsage>(() => new SamplingUsage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SamplingUsage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.UsageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SamplingUsage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SamplingUsage(SamplingUsage other) : this() {
      completionTokens_ = other.completionTokens_;
      reasoningTokens_ = other.reasoningTokens_;
      promptTokens_ = other.promptTokens_;
      totalTokens_ = other.totalTokens_;
      promptTextTokens_ = other.promptTextTokens_;
      cachedPromptTextTokens_ = other.cachedPromptTextTokens_;
      promptImageTokens_ = other.promptImageTokens_;
      numSourcesUsed_ = other.numSourcesUsed_;
      serverSideToolsUsed_ = other.serverSideToolsUsed_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SamplingUsage Clone() {
      return new SamplingUsage(this);
    }

    /// <summary>Field number for the "completion_tokens" field.</summary>
    public const int CompletionTokensFieldNumber = 1;
    private int completionTokens_;
    /// <summary>
    /// Total number of text completion tokens generated across all choices
    /// (in case of n>1).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CompletionTokens {
      get { return completionTokens_; }
      set {
        completionTokens_ = value;
      }
    }

    /// <summary>Field number for the "reasoning_tokens" field.</summary>
    public const int ReasoningTokensFieldNumber = 6;
    private int reasoningTokens_;
    /// <summary>
    /// Total number of reasoning tokens generated across all choices.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReasoningTokens {
      get { return reasoningTokens_; }
      set {
        reasoningTokens_ = value;
      }
    }

    /// <summary>Field number for the "prompt_tokens" field.</summary>
    public const int PromptTokensFieldNumber = 2;
    private int promptTokens_;
    /// <summary>
    /// Total number of prompt tokens (both text and images).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromptTokens {
      get { return promptTokens_; }
      set {
        promptTokens_ = value;
      }
    }

    /// <summary>Field number for the "total_tokens" field.</summary>
    public const int TotalTokensFieldNumber = 3;
    private int totalTokens_;
    /// <summary>
    /// Total number of tokens (prompt + completion).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalTokens {
      get { return totalTokens_; }
      set {
        totalTokens_ = value;
      }
    }

    /// <summary>Field number for the "prompt_text_tokens" field.</summary>
    public const int PromptTextTokensFieldNumber = 4;
    private int promptTextTokens_;
    /// <summary>
    /// Total number of (uncached) text tokens in the prompt.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromptTextTokens {
      get { return promptTextTokens_; }
      set {
        promptTextTokens_ = value;
      }
    }

    /// <summary>Field number for the "cached_prompt_text_tokens" field.</summary>
    public const int CachedPromptTextTokensFieldNumber = 7;
    private int cachedPromptTextTokens_;
    /// <summary>
    /// Total number of cached text tokens in the prompt.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CachedPromptTextTokens {
      get { return cachedPromptTextTokens_; }
      set {
        cachedPromptTextTokens_ = value;
      }
    }

    /// <summary>Field number for the "prompt_image_tokens" field.</summary>
    public const int PromptImageTokensFieldNumber = 5;
    private int promptImageTokens_;
    /// <summary>
    /// Total number of image tokens in the prompt.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromptImageTokens {
      get { return promptImageTokens_; }
      set {
        promptImageTokens_ = value;
      }
    }

    /// <summary>Field number for the "num_sources_used" field.</summary>
    public const int NumSourcesUsedFieldNumber = 8;
    private int numSourcesUsed_;
    /// <summary>
    /// Number of individual live search sources used.
    /// Only applicable when live search is enabled.
    /// e.g. If a live search query returns citations from both X and Web and news sources, this will be 3.
    /// If it returns citations from only X, this will be 1.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumSourcesUsed {
      get { return numSourcesUsed_; }
      set {
        numSourcesUsed_ = value;
      }
    }

    /// <summary>Field number for the "server_side_tools_used" field.</summary>
    public const int ServerSideToolsUsedFieldNumber = 9;
    private static readonly pb::FieldCodec<global::XaiApi.ServerSideTool> _repeated_serverSideToolsUsed_codec
        = pb::FieldCodec.ForEnum(74, x => (int) x, x => (global::XaiApi.ServerSideTool) x);
    private readonly pbc::RepeatedField<global::XaiApi.ServerSideTool> serverSideToolsUsed_ = new pbc::RepeatedField<global::XaiApi.ServerSideTool>();
    /// <summary>
    /// List of server side tools called.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::XaiApi.ServerSideTool> ServerSideToolsUsed {
      get { return serverSideToolsUsed_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SamplingUsage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SamplingUsage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CompletionTokens != other.CompletionTokens) return false;
      if (ReasoningTokens != other.ReasoningTokens) return false;
      if (PromptTokens != other.PromptTokens) return false;
      if (TotalTokens != other.TotalTokens) return false;
      if (PromptTextTokens != other.PromptTextTokens) return false;
      if (CachedPromptTextTokens != other.CachedPromptTextTokens) return false;
      if (PromptImageTokens != other.PromptImageTokens) return false;
      if (NumSourcesUsed != other.NumSourcesUsed) return false;
      if(!serverSideToolsUsed_.Equals(other.serverSideToolsUsed_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CompletionTokens != 0) hash ^= CompletionTokens.GetHashCode();
      if (ReasoningTokens != 0) hash ^= ReasoningTokens.GetHashCode();
      if (PromptTokens != 0) hash ^= PromptTokens.GetHashCode();
      if (TotalTokens != 0) hash ^= TotalTokens.GetHashCode();
      if (PromptTextTokens != 0) hash ^= PromptTextTokens.GetHashCode();
      if (CachedPromptTextTokens != 0) hash ^= CachedPromptTextTokens.GetHashCode();
      if (PromptImageTokens != 0) hash ^= PromptImageTokens.GetHashCode();
      if (NumSourcesUsed != 0) hash ^= NumSourcesUsed.GetHashCode();
      hash ^= serverSideToolsUsed_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CompletionTokens != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CompletionTokens);
      }
      if (PromptTokens != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PromptTokens);
      }
      if (TotalTokens != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalTokens);
      }
      if (PromptTextTokens != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PromptTextTokens);
      }
      if (PromptImageTokens != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PromptImageTokens);
      }
      if (ReasoningTokens != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ReasoningTokens);
      }
      if (CachedPromptTextTokens != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CachedPromptTextTokens);
      }
      if (NumSourcesUsed != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NumSourcesUsed);
      }
      serverSideToolsUsed_.WriteTo(output, _repeated_serverSideToolsUsed_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CompletionTokens != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CompletionTokens);
      }
      if (PromptTokens != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PromptTokens);
      }
      if (TotalTokens != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalTokens);
      }
      if (PromptTextTokens != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PromptTextTokens);
      }
      if (PromptImageTokens != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PromptImageTokens);
      }
      if (ReasoningTokens != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ReasoningTokens);
      }
      if (CachedPromptTextTokens != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CachedPromptTextTokens);
      }
      if (NumSourcesUsed != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NumSourcesUsed);
      }
      serverSideToolsUsed_.WriteTo(ref output, _repeated_serverSideToolsUsed_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CompletionTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CompletionTokens);
      }
      if (ReasoningTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReasoningTokens);
      }
      if (PromptTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromptTokens);
      }
      if (TotalTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalTokens);
      }
      if (PromptTextTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromptTextTokens);
      }
      if (CachedPromptTextTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CachedPromptTextTokens);
      }
      if (PromptImageTokens != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromptImageTokens);
      }
      if (NumSourcesUsed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumSourcesUsed);
      }
      size += serverSideToolsUsed_.CalculateSize(_repeated_serverSideToolsUsed_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SamplingUsage other) {
      if (other == null) {
        return;
      }
      if (other.CompletionTokens != 0) {
        CompletionTokens = other.CompletionTokens;
      }
      if (other.ReasoningTokens != 0) {
        ReasoningTokens = other.ReasoningTokens;
      }
      if (other.PromptTokens != 0) {
        PromptTokens = other.PromptTokens;
      }
      if (other.TotalTokens != 0) {
        TotalTokens = other.TotalTokens;
      }
      if (other.PromptTextTokens != 0) {
        PromptTextTokens = other.PromptTextTokens;
      }
      if (other.CachedPromptTextTokens != 0) {
        CachedPromptTextTokens = other.CachedPromptTextTokens;
      }
      if (other.PromptImageTokens != 0) {
        PromptImageTokens = other.PromptImageTokens;
      }
      if (other.NumSourcesUsed != 0) {
        NumSourcesUsed = other.NumSourcesUsed;
      }
      serverSideToolsUsed_.Add(other.serverSideToolsUsed_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CompletionTokens = input.ReadInt32();
            break;
          }
          case 16: {
            PromptTokens = input.ReadInt32();
            break;
          }
          case 24: {
            TotalTokens = input.ReadInt32();
            break;
          }
          case 32: {
            PromptTextTokens = input.ReadInt32();
            break;
          }
          case 40: {
            PromptImageTokens = input.ReadInt32();
            break;
          }
          case 48: {
            ReasoningTokens = input.ReadInt32();
            break;
          }
          case 56: {
            CachedPromptTextTokens = input.ReadInt32();
            break;
          }
          case 64: {
            NumSourcesUsed = input.ReadInt32();
            break;
          }
          case 74:
          case 72: {
            serverSideToolsUsed_.AddEntriesFrom(input, _repeated_serverSideToolsUsed_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CompletionTokens = input.ReadInt32();
            break;
          }
          case 16: {
            PromptTokens = input.ReadInt32();
            break;
          }
          case 24: {
            TotalTokens = input.ReadInt32();
            break;
          }
          case 32: {
            PromptTextTokens = input.ReadInt32();
            break;
          }
          case 40: {
            PromptImageTokens = input.ReadInt32();
            break;
          }
          case 48: {
            ReasoningTokens = input.ReadInt32();
            break;
          }
          case 56: {
            CachedPromptTextTokens = input.ReadInt32();
            break;
          }
          case 64: {
            NumSourcesUsed = input.ReadInt32();
            break;
          }
          case 74:
          case 72: {
            serverSideToolsUsed_.AddEntriesFrom(ref input, _repeated_serverSideToolsUsed_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Usage of embedding models.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EmbeddingUsage : pb::IMessage<EmbeddingUsage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmbeddingUsage> _parser = new pb::MessageParser<EmbeddingUsage>(() => new EmbeddingUsage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmbeddingUsage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XaiApi.UsageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbeddingUsage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbeddingUsage(EmbeddingUsage other) : this() {
      numTextEmbeddings_ = other.numTextEmbeddings_;
      numImageEmbeddings_ = other.numImageEmbeddings_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmbeddingUsage Clone() {
      return new EmbeddingUsage(this);
    }

    /// <summary>Field number for the "num_text_embeddings" field.</summary>
    public const int NumTextEmbeddingsFieldNumber = 1;
    private int numTextEmbeddings_;
    /// <summary>
    /// The number of feature vectors produced from text inputs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumTextEmbeddings {
      get { return numTextEmbeddings_; }
      set {
        numTextEmbeddings_ = value;
      }
    }

    /// <summary>Field number for the "num_image_embeddings" field.</summary>
    public const int NumImageEmbeddingsFieldNumber = 2;
    private int numImageEmbeddings_;
    /// <summary>
    /// The number of feature vectors produced from image inputs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumImageEmbeddings {
      get { return numImageEmbeddings_; }
      set {
        numImageEmbeddings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmbeddingUsage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmbeddingUsage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumTextEmbeddings != other.NumTextEmbeddings) return false;
      if (NumImageEmbeddings != other.NumImageEmbeddings) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumTextEmbeddings != 0) hash ^= NumTextEmbeddings.GetHashCode();
      if (NumImageEmbeddings != 0) hash ^= NumImageEmbeddings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumTextEmbeddings != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NumTextEmbeddings);
      }
      if (NumImageEmbeddings != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumImageEmbeddings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumTextEmbeddings != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NumTextEmbeddings);
      }
      if (NumImageEmbeddings != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumImageEmbeddings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumTextEmbeddings != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumTextEmbeddings);
      }
      if (NumImageEmbeddings != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumImageEmbeddings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmbeddingUsage other) {
      if (other == null) {
        return;
      }
      if (other.NumTextEmbeddings != 0) {
        NumTextEmbeddings = other.NumTextEmbeddings;
      }
      if (other.NumImageEmbeddings != 0) {
        NumImageEmbeddings = other.NumImageEmbeddings;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NumTextEmbeddings = input.ReadInt32();
            break;
          }
          case 16: {
            NumImageEmbeddings = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NumTextEmbeddings = input.ReadInt32();
            break;
          }
          case 16: {
            NumImageEmbeddings = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
